//===- CJIRVerifier.cpp - Cangjie IR Verifier --------------*- C++ -*------===//
//
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// This pass will verify whether the IR generated by the frontend of the cangjie
// meets the requirements.
//
//===----------------------------------------------------------------------===//

#include "llvm/Transforms/Scalar/CJIRVerifier.h"

#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/CJIntrinsics.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/SafepointIRVerifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/CJFillMetadata.h"
#include "llvm/Transforms/Scalar/ReflectionInfo.h"

using namespace llvm;
using namespace cangjie;

#define Assert(C, ...)                                                         \
  do {                                                                         \
    if (!(C)) {                                                                \
      checkFailed(__VA_ARGS__);                                                \
      return;                                                                  \
    }                                                                          \
  } while (false)

namespace {
class CJVerifier : public InstVisitor<CJVerifier> {
  // Befriend the base class so it can delegate to private visit methods.
  friend class InstVisitor<CJVerifier>;

public:
  CJVerifier(Module &M, raw_ostream *OS)
      : OS(OS), M(M), MST(&M), C(M.getContext()), DL(M.getDataLayout()) {
    EnableReflection = ReflectInfo::enable(M);
  }

  bool verify(Function &F) {
    Broken = false;
    visit(F);
    if (Broken) {
      errs() << "in function " << F.getName() << '\n';
    }
    return Broken;
  }

  bool verify(GlobalVariable &GV) {
    Broken = false;
    visitGlobalVariable(GV);
    if (Broken) {
      errs() << "in global value " << GV.getName() << '\n';
    }
    return Broken;
  }

  void visitGlobalVariable(GlobalVariable &GV) {
    if (GV.hasAttribute("CFileKlass")) {
      verifyTypeInfo(GV);
    } else if (GV.hasAttribute("cj_tt")) {
      verifyTypeTemplate(GV);
    }
  }

  void visitFunction(const Function &F) {
    // The c2cj and cjstub function is invoked by native function,
    // its struct param does not have a base pointer.
    if (F.hasFnAttribute("c2cj") || F.hasFnAttribute("cjstub"))
      return;

    // Verify the mut function's `this` parameter and its baseptr type.
    // If it is not a mut function, the gc pointer must be baseptr, and its
    // type should be i8 addrspace(1)*.

    FunctionType *FT = F.getFunctionType();
    AttributeList Attrs = F.getAttributes();
    bool HasSRet = false;

    // Verify parameter attributes.
    for (unsigned I = 0, E = FT->getNumParams(); I != E; ++I) {
      Type *Ty = FT->getParamType(I);
      PointerType *PT = dyn_cast<PointerType>(Ty);
      // Check only pointer-type parameters.
      if (!PT)
        continue;

      AttributeSet ArgAttrs = Attrs.getParamAttrs(I);
      if (ArgAttrs.hasAttribute(Attribute::StructRet)) {
        Assert(I == 0, "sret is not on the first parameter!", F.getArg(I));
        HasSRet = true;
        continue;
      }

      // HasRet: call func(sret*, i8 AS(1)* this, i8 AS(1)* basePtr...)
      // No Ret: call func(i8 AS(1)* this, i8 AS(1)* basePtr...)
      unsigned ThisIdx = HasSRet ? 1 : 0;
      if (I == ThisIdx && F.hasFnAttribute("record_mut")) {
        Assert(PT->getAddressSpace() == 1,
               "The mut this parameter be addrspace(1)*", F.getArg(I));
        unsigned BaseIdx = I + 1;
        auto *BasePtrTy = dyn_cast<PointerType>(FT->getParamType(BaseIdx));
        Assert(BasePtrTy, "The base pointer of this should be pointer type",
               F.getArg(BaseIdx));
        Assert(BasePtrTy == Type::getInt8PtrTy(C, 1),
               "The base pointer should be i8 addrspace(1)*",
               F.getArg(BaseIdx));
        continue;
      }

      if (isGCPointerType(PT))
        Assert(PT == Type::getInt8PtrTy(C, 1),
               "The gc pointer parameter should be i8 addrspace(1)*",
               F.getArg(I));
    }
    if (F.hasFnAttribute("native-interface-fn")) {
      for (auto &I : instructions(F)) {
        if (auto *CI = dyn_cast<CallBase>(&I)) {
          Assert(CI->getIntrinsicID() == Intrinsic::cj_get_type_info,
                 "native interface function only support llvm.cj.get.type.info",
                 CI);
        }
      }
    }
  }

  void visitAllocaInst(AllocaInst &AI) {
    Type *T = AI.getAllocatedType();
    if (auto *PT = dyn_cast<PointerType>(T)) {
      Type *ET = PT->getElementType();
      if (isGCPointerType(PT) && ET->isStructTy()) {
        checkFailed("Alloca %struct addrspace(1)* is not allowed.", &AI);
      }
      if (isGCPointerType(ET)) {
        checkFailed("Alloca addrspace(1)** is not allowed.", &AI);
      }

      if (!isa<StructType>(ET)) {
        return;
      }

      for (const User *U : AI.users()) {
        Assert(isa<StoreInst>(U) || isIntrinsicX(U, Intrinsic::dbg_declare),
               "Alloca struct* should only be used for dbg.declare", &AI);
      }
      return;
    }

    if (auto *AT = dyn_cast<ArrayType>(T)) {
      Assert(!isGCPointerType(AT->getElementType()),
             "The element type of array cannot be addrspace(1)*", &AI);
      return;
    }

    if (!isa<StructType>(T) || !containsGCPtrType(T)) {
      return;
    }

    bool hasMemset = false;
    for (const User *U : AI.users()) {
      auto *Cast = dyn_cast<BitCastInst>(U);
      if (!Cast) {
        continue;
      }
      for (const User *UU : Cast->users()) {
        if (isIntrinsicX(UU, Intrinsic::cj_memset)) {
          hasMemset = true;
          break;
        }
      }
    }
    Assert(hasMemset, "Missing cj.memset in allocation of structure.", &AI);
  }

  void visitCallBase(CallBase &Call) {
    Function *Callee = Call.getCalledFunction();
    if (Callee == nullptr) {
      return;
    }

    unsigned IID = Call.getIntrinsicID();
    switch (IID) {
    case Intrinsic::cj_alloca_generic: {
      Value *TIArg = Call.getArgOperand(0)->stripPointerCasts();
      if (auto *GV = dyn_cast<GlobalVariable>(TIArg)) {
        Assert(getTypeLayoutType(GV),
               "llvm.cj.alloca.generic layout type is null.", &Call);
      }
      break;
    }
    case Intrinsic::cj_gcwrite_static_struct:
    case Intrinsic::cj_gcread_static_struct: {
      // gcwrite/gcread.static.struct should have AggType Metadata.
      const MDNode *Metadata = Call.getMetadata("AggType");
      Assert(Metadata, "gcwrite/gcread.static.struct has no Metadata.", &Call);
      Assert(Metadata->getNumOperands() == 1,
             "AggType meta's size should be equal to 1!", &Call);

      StringRef STName =
          dyn_cast<MDString>(Metadata->getOperand(0).get())->getString();
      auto *ST = StructType::getTypeByName(C, STName);
      Assert(ST, "gcwrite/gcread.static.struct AggType doesn't exsit.", &Call);

      // The size should not be 0.
      auto *SizeArg = dyn_cast<ConstantInt>(getSize(&Call));
      if (SizeArg) {
        int64_t Size = SizeArg->getSExtValue();
        Assert(Size > 0, "gcwrite/gcread.static.struct size should not be 0.",
               &Call);
      }
      break;
    }
    case Intrinsic::cj_gcwrite_struct:
    case Intrinsic::cj_gcread_struct: {
      // The size should not be 0.
      auto *SizeArg = dyn_cast<ConstantInt>(getSize(&Call));
      if (SizeArg) {
        int64_t Size = SizeArg->getSExtValue();
        Assert(Size > 0, "gcwrite/gcread.struct size should not be 0.", &Call);
      }
      break;
    }
    case Intrinsic::memcpy:
    case Intrinsic::memmove: {
      Value *Dst = Call.getArgOperand(0);
      Value *Src = Call.getArgOperand(1);
      Value *SizeArg = Call.getArgOperand(2);
      auto *ConstantSize = dyn_cast<ConstantInt>(SizeArg);
      if (ConstantSize && ConstantSize->isZero())
        break;
      Type *DstCompleteTy = getCompleteTypedNonHeapObjectType(Dst, SizeArg);
      Type *SrcCompleteTy = getCompleteTypedNonHeapObjectType(Src, SizeArg);
      if (DstCompleteTy && DstCompleteTy == SrcCompleteTy)
        break;
      ReferencePayloadKind DstPayload =
          classifyReferencePayload(Dst, SizeArg);
      ReferencePayloadKind SrcPayload =
          classifyReferencePayload(Src, SizeArg);
      if (DstPayload == ReferencePayloadKind::ContainsReference ||
          SrcPayload == ReferencePayloadKind::ContainsReference) {
        checkFailed("Bare memcpy/memmove of reference payload must use "
                    "cj_array_copy_ref or another typed GC barrier.",
                    &Call);
        break;
      }
      if (DstPayload == ReferencePayloadKind::Unknown ||
          SrcPayload == ReferencePayloadKind::Unknown) {
        checkFailed("Bare memcpy/memmove payload provenance is unknown; use "
                    "cj_array_copy_ref, a typed helper, or supply typed "
                    "provenance.",
                    &Call);
      }
      break;
    }
    case Intrinsic::cj_get_mtable_func: {
      // funcPtr = call i8** @llvm.cj.get.mtable.func(i8* ti1, i8* ti2, i64 i)
      ConstantInt *IdxOpr = dyn_cast<ConstantInt>(Call.getArgOperand(2));
      if (IdxOpr == nullptr) {
        checkFailed("Called Function index should be constant int!", &Call);
      }
      break;
    }
    default:
      break;
    }

    // Verify invoke instructions for cangjie intrinsics.
    if (isa<InvokeInst>(&Call) && Callee->isCJIntrinsic()) {
      switch (IID) {
      default:
        checkFailed("Cannot invoke an intrinsic: ", &Call);
        break;
      case Intrinsic::cj_gc_statepoint:
      case Intrinsic::cj_malloc_object:
      case Intrinsic::cj_malloc_array:
      case Intrinsic::cj_malloc_array_generic:
      case Intrinsic::cj_division_check_sdiv:
      case Intrinsic::cj_division_check_udiv:
      case Intrinsic::cj_division_check_srem:
      case Intrinsic::cj_division_check_urem:
      case Intrinsic::cj_throw_exception:
      case Intrinsic::cj_alloca_generic:
        break;
      }
    }

    if (Callee->isDeclaration()) {
      return;
    }

    // If the function of callsite has debuginfo, the callsite must also have.
    if (Call.getFunction()->getSubprogram()) {
      Assert(Call.getDebugLoc() || Callee->hasFnAttribute(Attribute::NoInline),
             "The callsite debug info must have a !dbg location.", &Call);
    }
  }

  void visitAddrSpaceCastInst(AddrSpaceCastInst &I) {
    // The cj2c and c2cj function does not need to be verified, because
    // Frontend checking ensures that the functions does not transfer gcptr.
    for (const User *U : I.users()) {
      if (auto *CI = dyn_cast<CallBase>(U)) {
        Function *Callee = CI->getCalledFunction();
        if (Callee &&
            (Callee->hasFnAttribute("cj2c") || Callee->hasFnAttribute("c2cj")))
          return;
      }
      if (auto *II = dyn_cast<IntrinsicInst>(U))
        if (II->getIntrinsicID() == Intrinsic::cj_blackhole)
          return;
    }

    if (auto *II = dyn_cast<IntrinsicInst>(I.getOperand(0)))
      if (II->getIntrinsicID() == Intrinsic::cj_blackhole)
        return;

    for (const User *U : I.users()) {
      Assert(isa<StoreInst>(U) || isa<CallBase>(U),
             "Addrspacecast result can only be used for store or call.", &I);

      auto *SI = dyn_cast<StoreInst>(U);
      if (!SI)
        continue;

      const Value *Ptr = SI->getPointerOperand();
      for (const User *UU : Ptr->users()) {
        if (UU == U) {
          continue;
        }
        Assert(isIntrinsicX(UU, Intrinsic::dbg_declare),
               "If addrspacecast is used for store, it should only be used for "
               "dbg.declare",
               &I);
      }
      return;
    }

    Type *SrcTy = I.getOperand(0)->getType();
    Assert(SrcTy->isPointerTy(), "AddrSpaceCast source must be a pointer", &I);
    Assert((SrcTy->getNonOpaquePointerElementType()->isStructTy() ||
            SrcTy->getNonOpaquePointerElementType()->isArrayTy()),
           "Addrspacecast can only be used for struct* or array* conversion.",
           &I);

    // Verify that the addrspace cast is a transition from 0 to 1.
    Assert(I.getSrcAddressSpace() == 0,
           "AddrSpaceCast source must be addrspace(0)", &I);
    Assert(I.getDestAddressSpace() == 1,
           "AddrSpaceCast target must be addrspace(1)", &I);
  }

  void visitBitCastInst(BitCastInst &I) {
    // We only check the bitcast to i8* case.
    if (!isInt8AS0Pty(&I)) {
      return;
    }

    Value *Base = I.stripPointerCasts();
    if (!isa<AllocaInst>(Base) || !isMemoryContainsGCPtrType(Base->getType())) {
      return;
    }

    for (User *U : I.users()) {
      Assert(isa<CallBase>(U), "Bitcast struct* can only be callsite inst.",
             &I);
    }
  }

  void visitStoreInst(StoreInst &SI) {
    Value *Val = SI.getValueOperand();
    if (!Val->getType()->isPointerTy())
      return;

    Value *ValBase = findMemoryBasePointer(Val);
    Value *PtrBase = findMemoryBasePointer(SI.getPointerOperand());
    if (isGCPointerType(ValBase->getType()) &&
        isGCPointerType(PtrBase->getType())) {
      checkFailed("Need write barrier!", &SI);
    }

    if (isGCPointerType(ValBase->getType()) && isa<Constant>(PtrBase)) {
      checkFailed("Need write static barrier!", &SI);
    }
  }

  void visitLoadInst(LoadInst &LI) {
    if (!LI.getType()->isPointerTy())
      return;

    Value *PtrBase = findMemoryBasePointer(LI.getPointerOperand());
    if (isGCPointerType(LI.getType()) && isGCPointerType(PtrBase->getType())) {
      checkFailed("Need read barrier!", &LI);
    }

    if (isGCPointerType(LI.getType()) && isa<Constant>(PtrBase)) {
      checkFailed("Need read static barrier!", &LI);
    }
  }

private:
  raw_ostream *OS;
  const Module &M;
  ModuleSlotTracker MST;
  LLVMContext &C;
  const DataLayout &DL;
  bool EnableReflection = true;
  // Trace Check for Errors
  bool Broken = false;

  void verifyTypeInfo(GlobalVariable &GV) {
    TypeInfo Klass(&GV);
    if (Klass.isPureValueType())
      return;

    // check field data
    if (Klass.getFieldNum() > 0) {
      auto *FieldsTy = dyn_cast<ArrayType>(Klass.getFields()->getType());
      Assert(FieldsTy->getNumElements() == Klass.getFieldNum(),
             "Klass fields num error!", &GV);

      auto *OffsetsTy = dyn_cast<ArrayType>(Klass.getOffsets()->getType());
      Assert(OffsetsTy->getNumElements() == Klass.getFieldNum(),
             "Klass offsets num error!", &GV);

      StructType *ST = Klass.getLayoutType();
      Assert(ST, "Klass can not find RelatedType!", &GV);
      for (unsigned Idx = 0; Idx < Klass.getFieldNum(); Idx++) {
        if (Klass.isEnum())
          break;
        GlobalVariable *FieldGV = Klass.getField(Idx);
        if (!FieldGV->hasInitializer())
          continue;

        auto FieldType = ST->getElementType(Idx);
        auto FieldOffset = DL.getStructLayout(ST)->getElementOffset(Idx);
        TypeInfo FieldKlass(FieldGV);
        Assert(FieldOffset == Klass.getOffset(Idx), "Klass field offset error!",
               &GV);

        unsigned FieldSize = static_cast<unsigned>(
            DL.getTypeAllocSize(FieldType).getFixedSize());
        if (FieldKlass.isReferenceType()) {
          Assert(FieldSize == DL.getPointerSize(),
                 "Klass field memory size error!", &GV);
        } else {
          Assert(FieldSize == FieldKlass.getSize(),
                 "Klass field memory size error!", &GV);
          auto FieldAlign = DL.getABITypeAlignment(FieldType);
          Assert(FieldAlign == FieldKlass.getAlign(),
                 "Klass field align error!", &GV);
        }
      }
    }
    // check type args data
    if (Klass.getTypeArgNum() > 0) {
      Constant *TypeArgs = Klass.getTypeArgs();
      Assert(TypeArgs->getNumOperands() == Klass.getTypeArgNum(),
             "Klass typeArgs num error!", &GV);
    }
    // check array typeinfo data
    if (Klass.isArray()) {
      Assert(Klass.getSuperOrComponent(),
             "Array Klass has no element typeinfo!", &GV);
    }
    // check typetemplate
    if (auto Temp = Klass.getTypeTemplate()) {
      TypeTemplate TT(Temp);
      Assert(TT.getKind() == Klass.Kind, "typetemplate kind error!", &GV);
      Assert(TT.getFieldNum() == Klass.getFieldNum(),
             "typetemplate field num error!", &GV);
      Assert(TT.getTypeArgNum() == Klass.getTypeArgNum(),
             "typetemplate typeArgs num error!", &GV);
    }
    // check reflection
    auto ReflectMD = dyn_cast_or_null<MDTuple>(GV.getMetadata("Reflection"));
    if (ReflectMD != nullptr) {
      verifyReflection(ReflectMD, Klass.isEnum());
    }
  }

  void verifyTypeTemplate(GlobalVariable &GV) {
    TypeTemplate TT(&GV);
    // check reflection
    auto ReflectMD = dyn_cast_or_null<MDTuple>(GV.getMetadata("Reflection"));
    if (ReflectMD != nullptr) {
      verifyReflection(ReflectMD, TT.isEnum());
    }
  }

  void verifyReflection(MDTuple *ReflectMD, bool IsEnum) {
    if (IsEnum) {
      if (EnableReflection) {
        verifyEnumReflection(ReflectMD);
      } else {
        verifyEnumDebugInfo(ReflectMD);
      }
    } else {
      if (EnableReflection) {
        verifyDefaultReflection(ReflectMD);
      } else {
        verifyDefaultDebugInfo(ReflectMD);
      }
    }
  }

  // !{<name>, !{enum ctors}, !{instance methods}, !{static methods},
  //   !{ctor annotationMethods}, !{attributes}}
  void verifyEnumReflection(MDTuple *ReflectMD) {
    Assert(ReflectMD->getNumOperands() == ERT_MAX ||
           ReflectMD->getNumOperands() == ECRT_MAX,
           "EnumReflection format: operand numbers error!", ReflectMD);
    if (ReflectMD->getNumOperands() == ECRT_MAX) {
      const MDTuple *AttributeMD = getMDOperand(ReflectMD, ECRT_ATTRIBUTE);
      verifyReflectionAttribute(AttributeMD);
      return;
    }
    // check enum ctors
    const MDTuple *CtorMDs = getMDOperand(ReflectMD, ERT_ENUM_CTOR);
    for (unsigned Idx = 0; Idx < CtorMDs->getNumOperands(); ++Idx) {
      auto *CtorMD = dyn_cast<MDTuple>(CtorMDs->getOperand(Idx).get());
      // !{<ctor name>, <type name>}
      Assert(CtorMD->getNumOperands() == 2,
             "EnumReflection format: enum ctor number error!", ReflectMD);
    }
    // check instance method
    const MDTuple *MethodMDs = getMDOperand(ReflectMD, ERT_INSTANCE_METHOD);
    for (unsigned Idx = 0; Idx < MethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD = dyn_cast<MDTuple>(MethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check static method
    const MDTuple *StaticMethodMDs = getMDOperand(ReflectMD, ERT_STATIC_METHOD);
    for (unsigned Idx = 0; Idx < StaticMethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD =
          dyn_cast<MDTuple>(StaticMethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(ReflectMD, ERT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
    // check ctor annotation methods
    const MDTuple *CtorAnnoMDs = getMDOperand(ReflectMD, ERT_CTOR_ANNOTATIONS);
    for (unsigned Idx = 0; Idx < CtorAnnoMDs->getNumOperands(); ++Idx) {
      auto AnnoMethodName = getStringFromMD(CtorAnnoMDs, Idx);
      if (!AnnoMethodName.empty()) {
        Function *Func = M.getFunction(AnnoMethodName);
        Assert(Func, "Enum ctor annotation method not found!", ReflectMD);
      }
    }
  }

  // !{<name>, !{enum ctors}, !{attributes}}
  void verifyEnumDebugInfo(MDTuple *ReflectMD) {
    Assert(ReflectMD->getNumOperands() == EDT_MAX,
           "EnumDebugInfo format: operand numbers error!", ReflectMD);

    // check enum ctors
    const MDTuple *CtorMDs = getMDOperand(ReflectMD, EDT_ENUM_CTOR);
    for (unsigned Idx = 0; Idx < CtorMDs->getNumOperands(); ++Idx) {
      auto *CtorMD = dyn_cast<MDTuple>(CtorMDs->getOperand(Idx).get());
      // !{<ctor name>, <type name>}
      Assert(CtorMD->getNumOperands() == 2,
             "EnumDebugInfo format: enum ctor number error!", ReflectMD);
    }
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(ReflectMD, EDT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
  }

  // !{<name>, <declared generic class>, !{instance fields},!{static fields},
  // !{instance methods}, !{static methods}, !{type attributes}}
  void verifyDefaultReflection(MDTuple *ReflectMD) {
    Assert(ReflectMD->getNumOperands() == CRT_MAX,
           "Reflection format: operand numbers error!", ReflectMD);

    // check instance field
    const MDTuple *FieldMDs = getMDOperand(ReflectMD, CRT_INSTANCE_FIELD);
    for (unsigned Idx = 0; Idx < FieldMDs->getNumOperands(); ++Idx) {
      // !{Idx, field name, !{field attributes}}
      auto *FieldMD = dyn_cast<MDTuple>(FieldMDs->getOperand(Idx).get());
      Assert(FieldMD->getNumOperands() == 3,
             "Reflection format: field meta number error!", ReflectMD);
      // 2: attribute
      const MDTuple *AttributeMD = getMDOperand(FieldMD, 2);
      verifyReflectionAttribute(AttributeMD);
    }
    // check static field
    const MDTuple *StaticFieldMDs = getMDOperand(ReflectMD, CRT_STATIC_FIELD);
    for (unsigned Idx = 0; Idx < StaticFieldMDs->getNumOperands(); ++Idx) {
      // !{<name>, <type name>, <linkage name>, !{attributes}}
      auto *FieldMD = dyn_cast<MDTuple>(StaticFieldMDs->getOperand(Idx).get());
      Assert(FieldMD->getNumOperands() == 4,
             "Reflection format: static field meta number error!", ReflectMD);
      // 3: type attribute
      const MDTuple *AttributeMD = getMDOperand(FieldMD, 3);
      verifyReflectionAttribute(AttributeMD);
    }
    // check instance method
    const MDTuple *MethodMDs = getMDOperand(ReflectMD, CRT_INSTANCE_METHOD);
    for (unsigned Idx = 0; Idx < MethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD = dyn_cast<MDTuple>(MethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check static method
    const MDTuple *StaticMethodMDs = getMDOperand(ReflectMD, CRT_STATIC_METHOD);
    for (unsigned Idx = 0; Idx < StaticMethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD =
          dyn_cast<MDTuple>(StaticMethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(ReflectMD, CRT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
  }

  void verifyDefaultDebugInfo(MDTuple *ReflectMD) {
    // !{<name>, !{instance field}}
    Assert(ReflectMD->getNumOperands() == CDT_MAX,
           "EnumDebugInfo format: operand numbers error!", ReflectMD);
    // check instance field
    const MDTuple *FieldMDs = getMDOperand(ReflectMD, CDT_INSTANCE_FIELD);
    for (unsigned Idx = 0; Idx < FieldMDs->getNumOperands(); ++Idx) {
      // !{Idx, field name, !{field attributes}}
      auto *FieldMD = dyn_cast<MDTuple>(FieldMDs->getOperand(Idx).get());
      Assert(FieldMD->getNumOperands() == 3,
             "EnumDebugInfo format: field meta number error!", ReflectMD);
      // 2: attribute
      const MDTuple *AttributeMD = getMDOperand(FieldMD, 2);
      verifyReflectionAttribute(AttributeMD);
    }
  }

  // !{<name>, <return type>, <linkage name>, !{!actualParams},
  //   !{!genericParams}, !{attributes},}
  void verifyReflectionMethod(const MDTuple *MethodMD) {
    Assert(MethodMD->getNumOperands() == MRT_MAX,
           "Reflection format: method meta number error!", MethodMD);
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(MethodMD, MRT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
    // check actualParamInfo
    MDTuple *ActualParamMD = getMDOperand(MethodMD, MRT_ACTUAL_PARAM);
    for (unsigned Idx = 0; Idx < ActualParamMD->getNumOperands(); ++Idx) {
      auto *ParamTuple = dyn_cast<MDTuple>(ActualParamMD->getOperand(Idx));
      // {!param name, !type name, !attributes}
      Assert(ParamTuple->getNumOperands() == 3,
             "Reflection format: actual paramter number error!", MethodMD);
    }
    // cheeck genericParamInfo
    MDTuple *GenericParamMD = getMDOperand(MethodMD, MRT_GENERIC_PARAM);
    for (unsigned Idx = 0; Idx < GenericParamMD->getNumOperands(); ++Idx) {
      Assert(!getStringFromMD(GenericParamMD, Idx).empty(),
             "Reflection format: generic paramter error!", MethodMD);
    }
  }

  void verifyReflectionAttribute(const MDTuple *AttrMD) {
    unsigned NumOps = AttrMD->getNumOperands();
    Assert(NumOps > 0,
           "Reflection format: attribute metas must have annotation at least!",
           AttrMD);

    // last element is annotation info
    for (unsigned Idx = 0; Idx < NumOps - 1; ++Idx) {
      StringRef Mod = getStringFromMD(AttrMD, Idx);
      if (RMT_MAX == getTypeModifier(Mod))
        checkFailed("Reflection format: modifier type is invalid", AttrMD);
    }
  }

  StringRef getStringFromMD(const MDTuple *MD, unsigned Idx) {
    return dyn_cast<MDString>(MD->getOperand(Idx).get())->getString();
  }

  MDTuple *getMDOperand(const MDTuple *MD, unsigned Idx) {
    return dyn_cast<MDTuple>(MD->getOperand(Idx).get());
  }

  bool isIntrinsicX(const User *U, Intrinsic::ID IID) {
    if (auto *II = dyn_cast<IntrinsicInst>(U)) {
      if (II->getIntrinsicID() == IID) {
        return true;
      }
    }
    return false;
  }

  enum class ReferencePayloadKind { ContainsReference, NoReference, Unknown };

  // Stack/runtime roots are plain. A whole-object transfer between two typed
  // non-heap locations therefore needs no heap reference barrier. Keep this
  // proof deliberately narrower than address-space checks alone: both sides
  // must recover the same complete object type at offset zero.
  Type *getCompleteTypedNonHeapObjectType(Value *Ptr, Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || PtrTy->getAddressSpace() != 0 || !Size)
      return nullptr;

    APInt Offset(DL.getIndexSizeInBits(PtrTy->getAddressSpace()), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *BasePtrTy = dyn_cast<PointerType>(Base->getType());
    if (!BasePtrTy || BasePtrTy->getAddressSpace() != 0 ||
        BasePtrTy->isOpaque() || !Offset.isZero())
      return nullptr;

    Type *PayloadTy = BasePtrTy->getNonOpaquePointerElementType();
    if (!PayloadTy->isSized())
      return nullptr;
    auto AllocSize = DL.getTypeAllocSize(PayloadTy);
    if (AllocSize.isScalable() ||
        Size->getZExtValue() != AllocSize.getFixedSize())
      return nullptr;
    return PayloadTy;
  }

  // A bare memtransfer is legal only when typed provenance and a constant,
  // in-bounds range prove the copied bytes contain no managed references.
  // Type erasure, dynamic sizes, and ranges outside the recovered layout are
  // unknown and therefore rejected by the caller.
  ReferencePayloadKind classifyReferencePayload(Value *Ptr, Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    if (!PtrTy)
      return ReferencePayloadKind::Unknown;

    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!Size)
      return ReferencePayloadKind::Unknown;

    APInt Offset(DL.getIndexSizeInBits(PtrTy->getAddressSpace()), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *BasePtrTy = dyn_cast<PointerType>(Base->getType());
    if (!BasePtrTy || BasePtrTy->isOpaque())
      return ReferencePayloadKind::Unknown;

    Type *PayloadTy = BasePtrTy->getNonOpaquePointerElementType();
    // A bare i8* (argument, inttoptr, or another erased carrier) describes no
    // enclosing layout. An i8 alloca is still concrete typed storage.
    if (PayloadTy->isIntegerTy(8) && !isa<AllocaInst>(Base))
      return ReferencePayloadKind::Unknown;

    uint64_t CopySize = Size->getZExtValue();
    if (Offset.isNegative() || Offset.getActiveBits() > 64)
      return ReferencePayloadKind::Unknown;

    uint64_t Begin = Offset.getZExtValue();
    uint64_t End = Begin + CopySize;
    if (End < Begin)
      return ReferencePayloadKind::Unknown;

    uint64_t AllocSize = DL.getTypeAllocSize(PayloadTy).getFixedSize();
    if (Begin > AllocSize || End > AllocSize)
      return ReferencePayloadKind::Unknown;
    if (CopySize == 0)
      return ReferencePayloadKind::NoReference;
    if (!containsGCPtrType(PayloadTy))
      return ReferencePayloadKind::NoReference;

    SmallVector<uint64_t, 8> RefPositions;
    if (isGCPointerType(PayloadTy)) {
      RefPositions.push_back(0);
    } else if (auto *ST = dyn_cast<StructType>(PayloadTy)) {
      findReferencePositionInStruct(ST, 0, AllocSize, 0, RefPositions);
    } else if (auto *AT = dyn_cast<ArrayType>(PayloadTy)) {
      findReferencePositionInArray(AT, 0, AllocSize, 0, RefPositions);
    } else {
      // containsGCPtrType() also recognizes vectors.  Until a field-level
      // vector layout rule exists, rejecting the whole typed range is the
      // fail-closed answer.
      return ReferencePayloadKind::ContainsReference;
    }

    uint64_t RefSize = DL.getPointerSize(1);
    bool OverlapsReference = llvm::any_of(
        RefPositions, [Begin, End, RefSize](uint64_t Pos) {
          return Pos < End && Begin < Pos + RefSize;
        });
    return OverlapsReference ? ReferencePayloadKind::ContainsReference
                             : ReferencePayloadKind::NoReference;
  }

  bool findReferencePositions(Value *Ptr, uint64_t Size,
                              SmallVector<uint64_t, 8> &AllRefPos) {
    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *PtrBase = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    if (isGCPointerType(PtrBase->getType())) {
      report_fatal_error("The dst of memcpy base is gc pointer!");
      return true;
    }
    StructType *ST = dyn_cast<StructType>(
        PtrBase->getType()->getNonOpaquePointerElementType());
    if (!ST)
      return false;

    unsigned AllocSize =
        static_cast<unsigned>(DL.getTypeAllocSize(ST).getFixedSize());
    if (AllocSize < Size) {
      report_fatal_error("The memcpy size exceeds allocation size!");
      return false;
    }
    uint64_t BeginPos = Offset.getZExtValue();
    uint64_t EndPos = BeginPos + Size;
    findReferencePositionInStruct(ST, BeginPos, EndPos, 0, AllRefPos);
    return AllRefPos.size() != 0;
  }

  void findReferencePositionInStruct(StructType *ST, uint64_t BeginPos,
                                     uint64_t EndPos, uint64_t CurPos,
                                     SmallVector<uint64_t, 8> &AllRefPos) {
    for (uint64_t i = 0; i < ST->getNumElements(); i++) {
      uint64_t Offset = DL.getStructLayout(ST)->getElementOffset(i) + CurPos;
      Type *EleTy = ST->getElementType(i);
      uint64_t EleSize = DL.getTypeAllocSize(EleTy).getFixedSize();
      if (Offset + EleSize <= BeginPos)
        continue;
      if (Offset >= EndPos)
        return;
      if (isGCPointerType(EleTy)) {
        if (Offset >= BeginPos)
          AllRefPos.push_back(Offset);
      } else if (auto *EST = dyn_cast<StructType>(EleTy)) {
        findReferencePositionInStruct(EST, BeginPos, EndPos, Offset, AllRefPos);
      } else if (auto *EAT = dyn_cast<ArrayType>(EleTy)) {
        findReferencePositionInArray(EAT, BeginPos, EndPos, Offset, AllRefPos);
      }
    }
  }

  void findReferencePositionInArray(ArrayType *AT, uint64_t BeginPos,
                                    uint64_t EndPos, uint64_t CurPos,
                                    SmallVector<uint64_t, 8> &AllRefPos) {
    uint64_t EleNum = AT->getNumElements();
    Type *EleType = AT->getElementType();
    uint64_t EleSize = DL.getTypeAllocSize(EleType).getFixedSize();
    for (uint64_t Idx = 0; Idx < EleNum; Idx++) {
      uint64_t Offset = CurPos + Idx * EleSize;
      if (Offset + EleSize <= BeginPos)
        continue;
      if (Offset >= EndPos)
        return;
      if (isGCPointerType(EleType)) {
        if (Offset >= BeginPos)
          AllRefPos.push_back(Offset);
      } else if (auto *ArrayStruct = dyn_cast<StructType>(EleType)) {
        findReferencePositionInStruct(ArrayStruct, BeginPos, EndPos,
                                      Offset, AllRefPos);
      } else if (auto *NestedArray = dyn_cast<ArrayType>(EleType)) {
        findReferencePositionInArray(NestedArray, BeginPos, EndPos, Offset,
                                     AllRefPos);
      }
    }
  }

  void checkFailed(const Twine &Message, const Value *V) {
    *OS << Message << '\n';
    V->print(*OS, MST);
    *OS << '\n';
    Broken = true;
  }

  void checkFailed(const Twine &Message, const Metadata *MD) {
    *OS << Message << '\n';
    MD->print(*OS, MST, &M);
    *OS << '\n';
    Broken = true;
  }
};

} // namespace

static bool doCJIRVerify(Module &M) {
  Triple T(M.getTargetTriple());
  if (T.isARM())
    return false;
  bool Broken = false;
  CJVerifier CV(M, &dbgs());

  for (GlobalVariable &GV : M.globals()) {
    if (!GV.hasInitializer())
      continue;

    Broken |= CV.verify(GV);
    if (Broken)
      report_fatal_error("Broken global value found, compilation aborted!");
  }

  for (Function &F : M) {
    if (!F.hasCangjieGC())
      continue;

    Broken |= CV.verify(F);
    if (Broken)
      report_fatal_error("Broken function found, compilation aborted!");
  }
  return Broken;
}

PreservedAnalyses CJIRVerifier::run(Module &M, ModuleAnalysisManager &) const {
  if (hasRunCangjieOpt(M)) {
    return PreservedAnalyses::all();
  }
  if (doCJIRVerify(M)) {
    return PreservedAnalyses::none();
  }
  return PreservedAnalyses::all();
}
