//===- CJIRVerifier.cpp - Cangjie IR Verifier --------------*- C++ -*------===//
//
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// This pass will verify whether the IR generated by the frontend of the cangjie
// meets the requirements.
//
//===----------------------------------------------------------------------===//

#include "llvm/Transforms/Scalar/CJIRVerifier.h"

#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/CJIntrinsics.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/SafepointIRVerifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/CJFillMetadata.h"
#include "llvm/Transforms/Scalar/CJTypedReadHelper.h"
#include "llvm/Transforms/Scalar/ReflectionInfo.h"

#include <algorithm>
#include <cassert>

using namespace llvm;
using namespace cangjie;

#define Assert(C, ...)                                                         \
  do {                                                                         \
    if (!(C)) {                                                                \
      checkFailed(__VA_ARGS__);                                                \
      return;                                                                  \
    }                                                                          \
  } while (false)

namespace {
class CJVerifier : public InstVisitor<CJVerifier> {
  // Befriend the base class so it can delegate to private visit methods.
  friend class InstVisitor<CJVerifier>;

public:
  CJVerifier(Module &M, raw_ostream *OS)
      : OS(OS), M(M), MST(&M), C(M.getContext()), DL(M.getDataLayout()) {
    EnableReflection = ReflectInfo::enable(M);
  }

  bool verify(Function &F) {
    Broken = false;
    visit(F);
    if (Broken) {
      errs() << "in function " << F.getName() << '\n';
    }
    return Broken;
  }

  bool verify(GlobalVariable &GV) {
    Broken = false;
    visitGlobalVariable(GV);
    if (Broken) {
      errs() << "in global value " << GV.getName() << '\n';
    }
    return Broken;
  }

  void visitGlobalVariable(GlobalVariable &GV) {
    if (GV.hasAttribute("CFileKlass")) {
      verifyTypeInfo(GV);
    } else if (GV.hasAttribute("cj_tt")) {
      verifyTypeTemplate(GV);
    }
  }

  void visitFunction(const Function &F) {
    // The c2cj and cjstub function is invoked by native function,
    // its struct param does not have a base pointer.
    if (F.hasFnAttribute("c2cj") || F.hasFnAttribute("cjstub"))
      return;

    // Verify the mut function's `this` parameter and its baseptr type.
    // If it is not a mut function, the gc pointer must be baseptr, and its
    // type should be i8 addrspace(1)*.

    FunctionType *FT = F.getFunctionType();
    AttributeList Attrs = F.getAttributes();
    bool HasSRet = false;

    // Verify parameter attributes.
    for (unsigned I = 0, E = FT->getNumParams(); I != E; ++I) {
      Type *Ty = FT->getParamType(I);
      PointerType *PT = dyn_cast<PointerType>(Ty);
      // Check only pointer-type parameters.
      if (!PT)
        continue;

      AttributeSet ArgAttrs = Attrs.getParamAttrs(I);
      if (ArgAttrs.hasAttribute(Attribute::StructRet)) {
        Assert(I == 0, "sret is not on the first parameter!", F.getArg(I));
        HasSRet = true;
        continue;
      }

      // HasRet: call func(sret*, i8 AS(1)* this, i8 AS(1)* basePtr...)
      // No Ret: call func(i8 AS(1)* this, i8 AS(1)* basePtr...)
      unsigned ThisIdx = HasSRet ? 1 : 0;
      if (I == ThisIdx && F.hasFnAttribute("record_mut")) {
        Assert(PT->getAddressSpace() == 1,
               "The mut this parameter be addrspace(1)*", F.getArg(I));
        unsigned BaseIdx = I + 1;
        auto *BasePtrTy = dyn_cast<PointerType>(FT->getParamType(BaseIdx));
        Assert(BasePtrTy, "The base pointer of this should be pointer type",
               F.getArg(BaseIdx));
        Assert(BasePtrTy == Type::getInt8PtrTy(C, 1),
               "The base pointer should be i8 addrspace(1)*",
               F.getArg(BaseIdx));
        continue;
      }

      if (isGCPointerType(PT))
        Assert(PT == Type::getInt8PtrTy(C, 1),
               "The gc pointer parameter should be i8 addrspace(1)*",
               F.getArg(I));
    }
    if (F.hasFnAttribute("native-interface-fn")) {
      for (auto &I : instructions(F)) {
        if (auto *CI = dyn_cast<CallBase>(&I)) {
          Assert(CI->getIntrinsicID() == Intrinsic::cj_get_type_info,
                 "native interface function only support llvm.cj.get.type.info",
                 CI);
        }
      }
    }
  }

  void visitAllocaInst(AllocaInst &AI) {
    Type *T = AI.getAllocatedType();
    if (auto *PT = dyn_cast<PointerType>(T)) {
      Type *ET = PT->getElementType();
      if (isGCPointerType(PT) && ET->isStructTy()) {
        checkFailed("Alloca %struct addrspace(1)* is not allowed.", &AI);
      }
      if (isGCPointerType(ET)) {
        checkFailed("Alloca addrspace(1)** is not allowed.", &AI);
      }

      if (!isa<StructType>(ET)) {
        return;
      }

      for (const User *U : AI.users()) {
        Assert(isa<StoreInst>(U) || isIntrinsicX(U, Intrinsic::dbg_declare),
               "Alloca struct* should only be used for dbg.declare", &AI);
      }
      return;
    }

    if (auto *AT = dyn_cast<ArrayType>(T)) {
      Assert(!isGCPointerType(AT->getElementType()),
             "The element type of array cannot be addrspace(1)*", &AI);
      return;
    }

    if (!isa<StructType>(T) || !containsGCPtrType(T)) {
      return;
    }

    bool hasMemset = false;
    for (const User *U : AI.users()) {
      auto *Cast = dyn_cast<BitCastInst>(U);
      if (!Cast) {
        continue;
      }
      for (const User *UU : Cast->users()) {
        if (isIntrinsicX(UU, Intrinsic::cj_memset)) {
          hasMemset = true;
          break;
        }
      }
    }
    Assert(hasMemset, "Missing cj.memset in allocation of structure.", &AI);
  }

  void visitCallBase(CallBase &Call) {
    Function *Callee = Call.getCalledFunction();
    if (Callee == nullptr) {
      return;
    }

    unsigned IID = Call.getIntrinsicID();
    switch (IID) {
    case Intrinsic::cj_alloca_generic: {
      Value *TIArg = Call.getArgOperand(0)->stripPointerCasts();
      if (auto *GV = dyn_cast<GlobalVariable>(TIArg)) {
        Assert(getTypeLayoutType(GV),
               "llvm.cj.alloca.generic layout type is null.", &Call);
      }
      break;
    }
    case Intrinsic::cj_gcwrite_static_struct:
    case Intrinsic::cj_gcread_static_struct: {
      // gcwrite/gcread.static.struct should have AggType Metadata.
      const MDNode *Metadata = Call.getMetadata("AggType");
      Assert(Metadata, "gcwrite/gcread.static.struct has no Metadata.", &Call);
      Assert(Metadata->getNumOperands() == 1,
             "AggType meta's size should be equal to 1!", &Call);

      StringRef STName =
          dyn_cast<MDString>(Metadata->getOperand(0).get())->getString();
      auto *ST = StructType::getTypeByName(C, STName);
      Assert(ST, "gcwrite/gcread.static.struct AggType doesn't exsit.", &Call);

      // The size should not be 0.
      auto *SizeArg = dyn_cast<ConstantInt>(getSize(&Call));
      if (SizeArg) {
        int64_t Size = SizeArg->getSExtValue();
        Assert(Size > 0, "gcwrite/gcread.static.struct size should not be 0.",
               &Call);
      }
      break;
    }
    case Intrinsic::cj_copy_no_ref_struct: {
      const MDNode *Metadata = Call.getMetadata("AggType");
      Assert(Metadata,
             "llvm.cj.copy.no.ref.struct has no AggType metadata.", &Call);
      Assert(Metadata->getNumOperands() == 1,
             "llvm.cj.copy.no.ref.struct AggType must name one struct.",
             &Call);
      auto *TypeName =
          dyn_cast<MDString>(Metadata->getOperand(0).get());
      Assert(TypeName,
             "llvm.cj.copy.no.ref.struct AggType must be a string.", &Call);
      auto *ST = StructType::getTypeByName(C, TypeName->getString());
      Assert(ST && ST->isSized(),
             "llvm.cj.copy.no.ref.struct AggType must resolve to a sized "
             "concrete struct.",
             &Call);
      Assert(!containsGCPtrType(ST),
             "llvm.cj.copy.no.ref.struct AggType contains an AS1 field.",
             &Call);
      auto *SizeArg = dyn_cast<ConstantInt>(Call.getArgOperand(2));
      Assert(SizeArg && !SizeArg->isZero() &&
                 SizeArg->getValue().getActiveBits() <= 64,
             "llvm.cj.copy.no.ref.struct size must be a nonzero constant.",
             &Call);
      TypeSize StructSize = DL.getTypeAllocSize(ST);
      Assert(!StructSize.isScalable() &&
                 SizeArg->getZExtValue() == StructSize.getFixedSize(),
             "llvm.cj.copy.no.ref.struct size must equal AggType alloc size.",
             &Call);
      break;
    }
    case Intrinsic::cj_gcwrite_struct:
    case Intrinsic::cj_gcread_struct: {
      // The size should not be 0.
      auto *SizeArg = dyn_cast<ConstantInt>(getSize(&Call));
      if (SizeArg) {
        int64_t Size = SizeArg->getSExtValue();
        Assert(Size > 0, "gcwrite/gcread.struct size should not be 0.", &Call);
      }
      break;
    }
    case Intrinsic::memcpy:
    case Intrinsic::memmove: {
      Value *Dst = Call.getArgOperand(0);
      Value *Src = Call.getArgOperand(1);
      Value *SizeArg = Call.getArgOperand(2);
      auto *ConstantSize = dyn_cast<ConstantInt>(SizeArg);
      if (ConstantSize && ConstantSize->isZero())
        break;
      // Primitive ArrayLayout payloads have no managed-reference slots, so
      // their copy ranges do not require a GC barrier.  This type-only rule is
      // intentionally independent of allocation provenance and copy size.
      if (isPrimitiveArrayPayloadTransfer(Dst, Src))
        break;
      // The typed-read helper runs immediately after this verifier.  Admit
      // only its exact hand-off shape here; every other reference-bearing
      // transfer remains rejected below.
      if (auto *Copy = dyn_cast<MemTransferInst>(&Call))
        if (isCJTypedReadHelperCandidate(*Copy, DL))
          break;
      if (isNoReferenceMemTransfer(Dst, Src, SizeArg))
        break;
      if (auto *Copy = dyn_cast<MemTransferInst>(&Call))
        if (isNoAS1FieldCarrierMemTransfer(*Copy))
          break;
      Type *DstCompleteTy = getCompleteTypedNonHeapObjectType(Dst, SizeArg);
      Type *SrcCompleteTy = getCompleteTypedNonHeapObjectType(Src, SizeArg);
      // Both sides independently prove a complete typed non-heap object copy.
      // Managed-reference payloads additionally require equal byte offsets of
      // their GC pointer slots; heterogeneous layouts with different maps are
      // rejected before the generic provenance fallbacks.
      if (DstCompleteTy && SrcCompleteTy &&
          hasEqualGCPointerOffsets(DstCompleteTy, SrcCompleteTy) &&
          !isGlobalGCPointerDestination(Dst, DstCompleteTy)) {
        bool ContainsReference = containsGCPtrType(DstCompleteTy) ||
                                 containsGCPtrType(SrcCompleteTy);
        // Alloca-derived reference payloads must stay on the registered root
        // surface.  A global source is admitted only when it is the immutable
        // compiler-emitted cjstring literal form; arbitrary constant globals
        // do not carry that storage contract.
        if (!ContainsReference ||
            ((getRegisteredWholeObjectType(Dst, SizeArg) ||
              getCompleteTypedABISRetObjectType(Dst, SizeArg)) &&
             (getRegisteredWholeObjectType(Src, SizeArg) ||
              getCompleteTypedABIForwardedObjectType(Src, SizeArg) ||
              isCanonicalCJStringLiteralSource(Src, SizeArg))))
          break;
      }

      // A complete source object may be copied into a registered subobject of
      // an entry-block struct alloca.  This path is deliberately independent
      // from getCompleteTypedNonHeapObjectType: changing that shared helper
      // would also widen the zero-offset :254 path and the source side.
      if (isRegisteredSubObjectCopy(Dst, SrcCompleteTy, SizeArg))
        break;

      // Mirror of the registered-subobject admission above: a complete struct
      // subobject of a registered AS0 alloca or an ABI-forwarded source may
      // initialize a whole entry-block stack root when both layouts expose
      // exactly the same managed-reference slots.
      if (isRegisteredWholeObjectMirrorCopy(Dst, Src, SizeArg) &&
          classifyReferencePayload(Src, SizeArg) ==
              ReferencePayloadKind::ContainsReference)
        break;
      // Once both mirror surfaces are recovered, a layout mismatch or
      // unmodelled vector is a hard reject.  The generic payload classifier
      // treats missing vector slots as NoReference and would otherwise admit
      // them.
      if (Type *SrcSubObjectTy =
              getCompleteTypedStructSubObjectType(Src, SizeArg)) {
        Type *DstRootTy = getRegisteredWholeObjectType(Dst, SizeArg);
        if (DstRootTy && containsGCPtrType(SrcSubObjectTy) &&
            !hasEqualGCPointerOffsets(DstRootTy, SrcSubObjectTy)) {
          checkFailed("Bare memcpy/memmove of reference payload must use "
                      "cj_array_copy_ref or another typed GC barrier.",
                      &Call);
          break;
        }
      }
      ReferencePayloadKind SrcGenericPayload =
          classifyCompleteGenericPayload(Src, SizeArg);
      ReferencePayloadKind DstPayload =
          classifyCompleteGenericPayload(Dst, SizeArg);
      if (DstPayload == ReferencePayloadKind::Unknown)
        DstPayload = classifyCompleteArrayPayload(Dst, SizeArg);
      if (DstPayload == ReferencePayloadKind::Unknown)
        DstPayload = classifyReferencePayload(Dst, SizeArg);
      ReferencePayloadKind SrcPayload =
          SrcGenericPayload == ReferencePayloadKind::Unknown
              ? classifyCompleteArrayPayload(Src, SizeArg)
              : SrcGenericPayload;
      if (SrcPayload == ReferencePayloadKind::Unknown)
        SrcPayload = classifyReferencePayload(Src, SizeArg);
      // Cangjie lowers a payload of a canonical ABI base-pointer argument as
      //   bitcast (bitcast (gep (bitcast %base), 1) to %Payload AS1*) to i8*.
      // The exact header GEP plus complete pointee type proves source payload
      // provenance.  Local allocations are intentionally excluded here: they
      // must pass one of the stronger TypeInfo-based classifiers above.
      if (SrcPayload == ReferencePayloadKind::Unknown)
        SrcPayload = classifyTypedHeapPayload(Src, SizeArg);
      // The source must always independently prove NoReference.  The
      // destination must additionally be a complete, zero-offset typed
      // non-heap object whose recovered layout contains no managed pointer.
      // Address space alone is insufficient: an AS0 struct alloca may contain
      // AS1 fields and is then a tracked reference slot.
      if (SrcPayload == ReferencePayloadKind::NoReference &&
          DstCompleteTy && !containsGCPtrType(DstCompleteTy))
        break;
      if (DstPayload == ReferencePayloadKind::ContainsReference ||
          SrcPayload == ReferencePayloadKind::ContainsReference) {
        checkFailed("Bare memcpy/memmove of reference payload must use "
                    "cj_array_copy_ref or another typed GC barrier.",
                    &Call);
        break;
      }
      if (DstPayload == ReferencePayloadKind::Unknown ||
          SrcPayload == ReferencePayloadKind::Unknown) {
        checkFailed("Bare memcpy/memmove payload provenance is unknown; use "
                    "cj_array_copy_ref, a typed helper, or supply typed "
                    "provenance.",
                    &Call);
      }
      break;
    }
    case Intrinsic::cj_get_mtable_func: {
      // funcPtr = call i8** @llvm.cj.get.mtable.func(i8* ti1, i8* ti2, i64 i)
      ConstantInt *IdxOpr = dyn_cast<ConstantInt>(Call.getArgOperand(2));
      if (IdxOpr == nullptr) {
        checkFailed("Called Function index should be constant int!", &Call);
      }
      break;
    }
    default:
      break;
    }

    // Verify invoke instructions for cangjie intrinsics.
    if (isa<InvokeInst>(&Call) && Callee->isCJIntrinsic()) {
      switch (IID) {
      default:
        checkFailed("Cannot invoke an intrinsic: ", &Call);
        break;
      case Intrinsic::cj_gc_statepoint:
      case Intrinsic::cj_malloc_object:
      case Intrinsic::cj_malloc_array:
      case Intrinsic::cj_malloc_array_generic:
      case Intrinsic::cj_division_check_sdiv:
      case Intrinsic::cj_division_check_udiv:
      case Intrinsic::cj_division_check_srem:
      case Intrinsic::cj_division_check_urem:
      case Intrinsic::cj_throw_exception:
      case Intrinsic::cj_alloca_generic:
        break;
      }
    }

    if (Callee->isDeclaration()) {
      return;
    }

    // If the function of callsite has debuginfo, the callsite must also have.
    if (Call.getFunction()->getSubprogram()) {
      Assert(Call.getDebugLoc() || Callee->hasFnAttribute(Attribute::NoInline),
             "The callsite debug info must have a !dbg location.", &Call);
    }
  }

  void visitAddrSpaceCastInst(AddrSpaceCastInst &I) {
    // The cj2c and c2cj function does not need to be verified, because
    // Frontend checking ensures that the functions does not transfer gcptr.
    for (const User *U : I.users()) {
      if (auto *CI = dyn_cast<CallBase>(U)) {
        Function *Callee = CI->getCalledFunction();
        if (Callee &&
            (Callee->hasFnAttribute("cj2c") || Callee->hasFnAttribute("c2cj")))
          return;
      }
      if (auto *II = dyn_cast<IntrinsicInst>(U))
        if (II->getIntrinsicID() == Intrinsic::cj_blackhole)
          return;
    }

    if (auto *II = dyn_cast<IntrinsicInst>(I.getOperand(0)))
      if (II->getIntrinsicID() == Intrinsic::cj_blackhole)
        return;

    for (const User *U : I.users()) {
      Assert(isa<StoreInst>(U) || isa<CallBase>(U),
             "Addrspacecast result can only be used for store or call.", &I);

      auto *SI = dyn_cast<StoreInst>(U);
      if (!SI)
        continue;

      const Value *Ptr = SI->getPointerOperand();
      for (const User *UU : Ptr->users()) {
        if (UU == U) {
          continue;
        }
        Assert(isIntrinsicX(UU, Intrinsic::dbg_declare),
               "If addrspacecast is used for store, it should only be used for "
               "dbg.declare",
               &I);
      }
      return;
    }

    Type *SrcTy = I.getOperand(0)->getType();
    Assert(SrcTy->isPointerTy(), "AddrSpaceCast source must be a pointer", &I);
    Assert((SrcTy->getNonOpaquePointerElementType()->isStructTy() ||
            SrcTy->getNonOpaquePointerElementType()->isArrayTy()),
           "Addrspacecast can only be used for struct* or array* conversion.",
           &I);

    // Verify that the addrspace cast is a transition from 0 to 1.
    Assert(I.getSrcAddressSpace() == 0,
           "AddrSpaceCast source must be addrspace(0)", &I);
    Assert(I.getDestAddressSpace() == 1,
           "AddrSpaceCast target must be addrspace(1)", &I);
  }

  void visitBitCastInst(BitCastInst &I) {
    // We only check the bitcast to i8* case.
    if (!isInt8AS0Pty(&I)) {
      return;
    }

    Value *Base = I.stripPointerCasts();
    if (!isa<AllocaInst>(Base) || !isMemoryContainsGCPtrType(Base->getType())) {
      return;
    }

    for (User *U : I.users()) {
      Assert(isa<CallBase>(U), "Bitcast struct* can only be callsite inst.",
             &I);
    }
  }

  void visitStoreInst(StoreInst &SI) {
    Value *Val = SI.getValueOperand();
    if (!Val->getType()->isPointerTy())
      return;

    Value *ValBase = findMemoryBasePointer(Val);
    Value *PtrBase = findMemoryBasePointer(SI.getPointerOperand());
    if (isGCPointerType(ValBase->getType()) &&
        isGCPointerType(PtrBase->getType())) {
      checkFailed("Need write barrier!", &SI);
    }

    if (isGCPointerType(ValBase->getType()) && isa<Constant>(PtrBase)) {
      checkFailed("Need write static barrier!", &SI);
    }
  }

  void visitLoadInst(LoadInst &LI) {
    if (!LI.getType()->isPointerTy())
      return;

    Value *PtrBase = findMemoryBasePointer(LI.getPointerOperand());
    if (isGCPointerType(LI.getType()) && isGCPointerType(PtrBase->getType())) {
      checkFailed("Need read barrier!", &LI);
    }

    if (isGCPointerType(LI.getType()) && isa<Constant>(PtrBase)) {
      checkFailed("Need read static barrier!", &LI);
    }
  }

private:
  raw_ostream *OS;
  const Module &M;
  ModuleSlotTracker MST;
  LLVMContext &C;
  const DataLayout &DL;
  bool EnableReflection = true;
  // Trace Check for Errors
  bool Broken = false;

  void verifyTypeInfo(GlobalVariable &GV) {
    TypeInfo Klass(&GV);
    if (Klass.isPureValueType())
      return;

    // check field data
    if (Klass.getFieldNum() > 0) {
      auto *FieldsTy = dyn_cast<ArrayType>(Klass.getFields()->getType());
      Assert(FieldsTy->getNumElements() == Klass.getFieldNum(),
             "Klass fields num error!", &GV);

      auto *OffsetsTy = dyn_cast<ArrayType>(Klass.getOffsets()->getType());
      Assert(OffsetsTy->getNumElements() == Klass.getFieldNum(),
             "Klass offsets num error!", &GV);

      StructType *ST = Klass.getLayoutType();
      Assert(ST, "Klass can not find RelatedType!", &GV);
      for (unsigned Idx = 0; Idx < Klass.getFieldNum(); Idx++) {
        if (Klass.isEnum())
          break;
        GlobalVariable *FieldGV = Klass.getField(Idx);
        if (!FieldGV->hasInitializer())
          continue;

        auto FieldType = ST->getElementType(Idx);
        auto FieldOffset = DL.getStructLayout(ST)->getElementOffset(Idx);
        TypeInfo FieldKlass(FieldGV);
        Assert(FieldOffset == Klass.getOffset(Idx), "Klass field offset error!",
               &GV);

        unsigned FieldSize = static_cast<unsigned>(
            DL.getTypeAllocSize(FieldType).getFixedSize());
        if (FieldKlass.isReferenceType()) {
          Assert(FieldSize == DL.getPointerSize(),
                 "Klass field memory size error!", &GV);
        } else {
          Assert(FieldSize == FieldKlass.getSize(),
                 "Klass field memory size error!", &GV);
          auto FieldAlign = DL.getABITypeAlignment(FieldType);
          Assert(FieldAlign == FieldKlass.getAlign(),
                 "Klass field align error!", &GV);
        }
      }
    }
    // check type args data
    if (Klass.getTypeArgNum() > 0) {
      Constant *TypeArgs = Klass.getTypeArgs();
      Assert(TypeArgs->getNumOperands() == Klass.getTypeArgNum(),
             "Klass typeArgs num error!", &GV);
    }
    // check array typeinfo data
    if (Klass.isArray()) {
      Assert(Klass.getSuperOrComponent(),
             "Array Klass has no element typeinfo!", &GV);
    }
    // check typetemplate
    if (auto Temp = Klass.getTypeTemplate()) {
      TypeTemplate TT(Temp);
      Assert(TT.getKind() == Klass.Kind, "typetemplate kind error!", &GV);
      Assert(TT.getFieldNum() == Klass.getFieldNum(),
             "typetemplate field num error!", &GV);
      Assert(TT.getTypeArgNum() == Klass.getTypeArgNum(),
             "typetemplate typeArgs num error!", &GV);
    }
    // check reflection
    auto ReflectMD = dyn_cast_or_null<MDTuple>(GV.getMetadata("Reflection"));
    if (ReflectMD != nullptr) {
      verifyReflection(ReflectMD, Klass.isEnum());
    }
  }

  void verifyTypeTemplate(GlobalVariable &GV) {
    TypeTemplate TT(&GV);
    // check reflection
    auto ReflectMD = dyn_cast_or_null<MDTuple>(GV.getMetadata("Reflection"));
    if (ReflectMD != nullptr) {
      verifyReflection(ReflectMD, TT.isEnum());
    }
  }

  void verifyReflection(MDTuple *ReflectMD, bool IsEnum) {
    if (IsEnum) {
      if (EnableReflection) {
        verifyEnumReflection(ReflectMD);
      } else {
        verifyEnumDebugInfo(ReflectMD);
      }
    } else {
      if (EnableReflection) {
        verifyDefaultReflection(ReflectMD);
      } else {
        verifyDefaultDebugInfo(ReflectMD);
      }
    }
  }

  // !{<name>, !{enum ctors}, !{instance methods}, !{static methods},
  //   !{ctor annotationMethods}, !{attributes}}
  void verifyEnumReflection(MDTuple *ReflectMD) {
    Assert(ReflectMD->getNumOperands() == ERT_MAX ||
           ReflectMD->getNumOperands() == ECRT_MAX,
           "EnumReflection format: operand numbers error!", ReflectMD);
    if (ReflectMD->getNumOperands() == ECRT_MAX) {
      const MDTuple *AttributeMD = getMDOperand(ReflectMD, ECRT_ATTRIBUTE);
      verifyReflectionAttribute(AttributeMD);
      return;
    }
    // check enum ctors
    const MDTuple *CtorMDs = getMDOperand(ReflectMD, ERT_ENUM_CTOR);
    for (unsigned Idx = 0; Idx < CtorMDs->getNumOperands(); ++Idx) {
      auto *CtorMD = dyn_cast<MDTuple>(CtorMDs->getOperand(Idx).get());
      // !{<ctor name>, <type name>}
      Assert(CtorMD->getNumOperands() == 2,
             "EnumReflection format: enum ctor number error!", ReflectMD);
    }
    // check instance method
    const MDTuple *MethodMDs = getMDOperand(ReflectMD, ERT_INSTANCE_METHOD);
    for (unsigned Idx = 0; Idx < MethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD = dyn_cast<MDTuple>(MethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check static method
    const MDTuple *StaticMethodMDs = getMDOperand(ReflectMD, ERT_STATIC_METHOD);
    for (unsigned Idx = 0; Idx < StaticMethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD =
          dyn_cast<MDTuple>(StaticMethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(ReflectMD, ERT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
    // check ctor annotation methods
    const MDTuple *CtorAnnoMDs = getMDOperand(ReflectMD, ERT_CTOR_ANNOTATIONS);
    for (unsigned Idx = 0; Idx < CtorAnnoMDs->getNumOperands(); ++Idx) {
      auto AnnoMethodName = getStringFromMD(CtorAnnoMDs, Idx);
      if (!AnnoMethodName.empty()) {
        Function *Func = M.getFunction(AnnoMethodName);
        Assert(Func, "Enum ctor annotation method not found!", ReflectMD);
      }
    }
  }

  // !{<name>, !{enum ctors}, !{attributes}}
  void verifyEnumDebugInfo(MDTuple *ReflectMD) {
    Assert(ReflectMD->getNumOperands() == EDT_MAX,
           "EnumDebugInfo format: operand numbers error!", ReflectMD);

    // check enum ctors
    const MDTuple *CtorMDs = getMDOperand(ReflectMD, EDT_ENUM_CTOR);
    for (unsigned Idx = 0; Idx < CtorMDs->getNumOperands(); ++Idx) {
      auto *CtorMD = dyn_cast<MDTuple>(CtorMDs->getOperand(Idx).get());
      // !{<ctor name>, <type name>}
      Assert(CtorMD->getNumOperands() == 2,
             "EnumDebugInfo format: enum ctor number error!", ReflectMD);
    }
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(ReflectMD, EDT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
  }

  // !{<name>, <declared generic class>, !{instance fields},!{static fields},
  // !{instance methods}, !{static methods}, !{type attributes}}
  void verifyDefaultReflection(MDTuple *ReflectMD) {
    Assert(ReflectMD->getNumOperands() == CRT_MAX,
           "Reflection format: operand numbers error!", ReflectMD);

    // check instance field
    const MDTuple *FieldMDs = getMDOperand(ReflectMD, CRT_INSTANCE_FIELD);
    for (unsigned Idx = 0; Idx < FieldMDs->getNumOperands(); ++Idx) {
      // !{Idx, field name, !{field attributes}}
      auto *FieldMD = dyn_cast<MDTuple>(FieldMDs->getOperand(Idx).get());
      Assert(FieldMD->getNumOperands() == 3,
             "Reflection format: field meta number error!", ReflectMD);
      // 2: attribute
      const MDTuple *AttributeMD = getMDOperand(FieldMD, 2);
      verifyReflectionAttribute(AttributeMD);
    }
    // check static field
    const MDTuple *StaticFieldMDs = getMDOperand(ReflectMD, CRT_STATIC_FIELD);
    for (unsigned Idx = 0; Idx < StaticFieldMDs->getNumOperands(); ++Idx) {
      // !{<name>, <type name>, <linkage name>, !{attributes}}
      auto *FieldMD = dyn_cast<MDTuple>(StaticFieldMDs->getOperand(Idx).get());
      Assert(FieldMD->getNumOperands() == 4,
             "Reflection format: static field meta number error!", ReflectMD);
      // 3: type attribute
      const MDTuple *AttributeMD = getMDOperand(FieldMD, 3);
      verifyReflectionAttribute(AttributeMD);
    }
    // check instance method
    const MDTuple *MethodMDs = getMDOperand(ReflectMD, CRT_INSTANCE_METHOD);
    for (unsigned Idx = 0; Idx < MethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD = dyn_cast<MDTuple>(MethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check static method
    const MDTuple *StaticMethodMDs = getMDOperand(ReflectMD, CRT_STATIC_METHOD);
    for (unsigned Idx = 0; Idx < StaticMethodMDs->getNumOperands(); ++Idx) {
      auto *MethodMD =
          dyn_cast<MDTuple>(StaticMethodMDs->getOperand(Idx).get());
      verifyReflectionMethod(MethodMD);
    }
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(ReflectMD, CRT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
  }

  void verifyDefaultDebugInfo(MDTuple *ReflectMD) {
    // !{<name>, !{instance field}}
    Assert(ReflectMD->getNumOperands() == CDT_MAX,
           "EnumDebugInfo format: operand numbers error!", ReflectMD);
    // check instance field
    const MDTuple *FieldMDs = getMDOperand(ReflectMD, CDT_INSTANCE_FIELD);
    for (unsigned Idx = 0; Idx < FieldMDs->getNumOperands(); ++Idx) {
      // !{Idx, field name, !{field attributes}}
      auto *FieldMD = dyn_cast<MDTuple>(FieldMDs->getOperand(Idx).get());
      Assert(FieldMD->getNumOperands() == 3,
             "EnumDebugInfo format: field meta number error!", ReflectMD);
      // 2: attribute
      const MDTuple *AttributeMD = getMDOperand(FieldMD, 2);
      verifyReflectionAttribute(AttributeMD);
    }
  }

  // !{<name>, <return type>, <linkage name>, !{!actualParams},
  //   !{!genericParams}, !{attributes},}
  void verifyReflectionMethod(const MDTuple *MethodMD) {
    Assert(MethodMD->getNumOperands() == MRT_MAX,
           "Reflection format: method meta number error!", MethodMD);
    // check type attribute
    const MDTuple *AttributeMD = getMDOperand(MethodMD, MRT_ATTRIBUTE);
    verifyReflectionAttribute(AttributeMD);
    // check actualParamInfo
    MDTuple *ActualParamMD = getMDOperand(MethodMD, MRT_ACTUAL_PARAM);
    for (unsigned Idx = 0; Idx < ActualParamMD->getNumOperands(); ++Idx) {
      auto *ParamTuple = dyn_cast<MDTuple>(ActualParamMD->getOperand(Idx));
      // {!param name, !type name, !attributes}
      Assert(ParamTuple->getNumOperands() == 3,
             "Reflection format: actual paramter number error!", MethodMD);
    }
    // cheeck genericParamInfo
    MDTuple *GenericParamMD = getMDOperand(MethodMD, MRT_GENERIC_PARAM);
    for (unsigned Idx = 0; Idx < GenericParamMD->getNumOperands(); ++Idx) {
      Assert(!getStringFromMD(GenericParamMD, Idx).empty(),
             "Reflection format: generic paramter error!", MethodMD);
    }
  }

  void verifyReflectionAttribute(const MDTuple *AttrMD) {
    unsigned NumOps = AttrMD->getNumOperands();
    Assert(NumOps > 0,
           "Reflection format: attribute metas must have annotation at least!",
           AttrMD);

    // last element is annotation info
    for (unsigned Idx = 0; Idx < NumOps - 1; ++Idx) {
      StringRef Mod = getStringFromMD(AttrMD, Idx);
      if (RMT_MAX == getTypeModifier(Mod))
        checkFailed("Reflection format: modifier type is invalid", AttrMD);
    }
  }

  StringRef getStringFromMD(const MDTuple *MD, unsigned Idx) {
    return dyn_cast<MDString>(MD->getOperand(Idx).get())->getString();
  }

  MDTuple *getMDOperand(const MDTuple *MD, unsigned Idx) {
    return dyn_cast<MDTuple>(MD->getOperand(Idx).get());
  }

  bool isIntrinsicX(const User *U, Intrinsic::ID IID) {
    if (auto *II = dyn_cast<IntrinsicInst>(U)) {
      if (II->getIntrinsicID() == IID) {
        return true;
      }
    }
    return false;
  }

  enum class ReferencePayloadKind { ContainsReference, NoReference, Unknown };

  // Recover the complete payload layout of the canonical
  //   alloca.generic -> bitcast -> GEP(one TypeInfo pointer) -> bitcast
  // chain.  Any dynamic/interior carrier or inconsistent size remains
  // unknown.  A recovered reference-bearing layout is reported explicitly so
  // the caller retains the ContainsReference diagnostic.
  ReferencePayloadKind classifyCompleteGenericPayload(Value *Ptr,
                                                       Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *CopySize = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || !CopySize)
      return ReferencePayloadKind::Unknown;

    APInt Offset(DL.getIndexSizeInBits(PtrTy->getAddressSpace()), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *Allocation = dyn_cast<IntrinsicInst>(Base);
    if (!Allocation ||
        Allocation->getIntrinsicID() != Intrinsic::cj_alloca_generic)
      return ReferencePayloadKind::Unknown;

    uint64_t HeaderSize =
        DL.getTypeAllocSize(Type::getInt8PtrTy(C)).getFixedSize();
    if (Offset.isNegative() || Offset.getActiveBits() > 64 ||
        Offset.getZExtValue() != HeaderSize)
      return ReferencePayloadKind::Unknown;

    auto *AllocationSize =
        dyn_cast<ConstantInt>(Allocation->getArgOperand(1));
    auto *TI = dyn_cast<GlobalVariable>(
        Allocation->getArgOperand(0)->stripPointerCasts());
    if (!AllocationSize || !TI)
      return ReferencePayloadKind::Unknown;

    StructType *PayloadTy = getTypeLayoutType(TI);
    if (!PayloadTy || !PayloadTy->isSized())
      return ReferencePayloadKind::Unknown;
    TypeSize PayloadSize = DL.getTypeAllocSize(PayloadTy);
    if (PayloadSize.isScalable())
      return ReferencePayloadKind::Unknown;

    uint64_t Size = PayloadSize.getFixedSize();
    if (CopySize->getZExtValue() != Size ||
        AllocationSize->getZExtValue() != Size)
      return ReferencePayloadKind::Unknown;
    return containsGCPtrType(PayloadTy)
               ? ReferencePayloadKind::ContainsReference
               : ReferencePayloadKind::NoReference;
  }

  ReferencePayloadKind classifyTypedHeapPayload(Value *Ptr,
                                                 Value *SizeValue) {
    auto *CopySize = dyn_cast<ConstantInt>(SizeValue);
    auto *OuterCast = dyn_cast<BitCastInst>(Ptr);
    if (!CopySize || !OuterCast ||
        OuterCast->getDestTy() != Type::getInt8PtrTy(C, 1))
      return ReferencePayloadKind::Unknown;

    auto *PayloadPtrTy = dyn_cast<PointerType>(OuterCast->getSrcTy());
    if (!PayloadPtrTy || PayloadPtrTy->getAddressSpace() != 1 ||
        PayloadPtrTy->isOpaque())
      return ReferencePayloadKind::Unknown;
    Type *PayloadTy = PayloadPtrTy->getNonOpaquePointerElementType();
    if (!PayloadTy->isSized())
      return ReferencePayloadKind::Unknown;
    TypeSize PayloadSize = DL.getTypeAllocSize(PayloadTy);
    if (PayloadSize.isScalable() ||
        CopySize->getZExtValue() != PayloadSize.getFixedSize())
      return ReferencePayloadKind::Unknown;

    auto *InnerCast = dyn_cast<BitCastInst>(OuterCast->getOperand(0));
    if (!InnerCast)
      return ReferencePayloadKind::Unknown;

    auto *GEP = dyn_cast<GetElementPtrInst>(InnerCast->getOperand(0));
    if (!GEP || GEP->getNumIndices() != 1 ||
        GEP->getSourceElementType() != Type::getInt8PtrTy(C) ||
        GEP->getAddressSpace() != 1)
      return ReferencePayloadKind::Unknown;
    auto *HeaderIndex = dyn_cast<ConstantInt>(GEP->idx_begin()->get());
    if (!HeaderIndex || !HeaderIndex->isOne())
      return ReferencePayloadKind::Unknown;

    auto *BaseCast = dyn_cast<BitCastInst>(GEP->getPointerOperand());
    if (!BaseCast || BaseCast->getSrcTy() != Type::getInt8PtrTy(C, 1) ||
        BaseCast->getDestTy() != PointerType::get(Type::getInt8PtrTy(C), 1))
      return ReferencePayloadKind::Unknown;

    // visitFunction verifies that non-mutator-this GC pointer parameters are
    // canonical i8 AS1 base pointers.  Restrict this typed fallback to that
    // ABI provenance; selects, PHIs, interior pointers, and locally fabricated
    // allocation chains remain Unknown.
    auto *BaseArg = dyn_cast<Argument>(BaseCast->getOperand(0));
    if (!BaseArg)
      return ReferencePayloadKind::Unknown;
    Function *Parent = BaseArg->getParent();
    bool HasSRet = Parent->arg_size() != 0 &&
                   Parent->getAttributes()
                       .getParamAttrs(0)
                       .hasAttribute(Attribute::StructRet);
    unsigned ThisIndex = HasSRet ? 1 : 0;
    if (Parent->hasFnAttribute("record_mut") &&
        BaseArg->getArgNo() == ThisIndex)
      return ReferencePayloadKind::Unknown;

    return containsGCPtrType(PayloadTy)
               ? ReferencePayloadKind::ContainsReference
               : ReferencePayloadKind::NoReference;
  }

  // Recover E from one unique
  //   %ArrayLayout.T = type { %ArrayBase, [0 x E] }
  // payload-selection GEP in a pointer-identity chain.  GEPs after the
  // selector may index E directly or operate on its i8 carrier; neither
  // changes whether E contains a managed-reference slot.  GEPs before the
  // selector are deliberately unconstrained because allocation provenance is
  // not part of this type-only rule.
  Type *getUniqueArrayLayoutElementType(Value *Ptr) {
    Type *ElementTy = nullptr;
    SmallVector<const GEPOperator *, 4> DescendantGEPs;

    for (Value *Current = Ptr;;) {
      if (auto *Cast = dyn_cast<BitCastOperator>(Current)) {
        Current = Cast->getOperand(0);
        continue;
      }
      if (auto *Cast = dyn_cast<AddrSpaceCastOperator>(Current)) {
        Current = Cast->getOperand(0);
        continue;
      }

      auto *GEP = dyn_cast<GEPOperator>(Current);
      if (!GEP)
        break;

      auto *LayoutTy = dyn_cast<StructType>(GEP->getSourceElementType());
      ArrayType *FlexibleArrayTy = nullptr;
      bool IsPayloadSelector = false;
      if (LayoutTy && LayoutTy->hasName() &&
          LayoutTy->getName().startswith("ArrayLayout.") &&
          LayoutTy->getNumElements() == 2) {
        auto *ArrayBaseTy = dyn_cast<StructType>(LayoutTy->getElementType(0));
        FlexibleArrayTy = dyn_cast<ArrayType>(LayoutTy->getElementType(1));
        auto Index = GEP->idx_begin();
        auto *Zero = GEP->getNumIndices() == 2
                         ? dyn_cast<ConstantInt>(Index->get())
                         : nullptr;
        auto *One = Zero ? dyn_cast<ConstantInt>((++Index)->get()) : nullptr;
        IsPayloadSelector =
            ArrayBaseTy && ArrayBaseTy->hasName() &&
            ArrayBaseTy->getName() == "ArrayBase" && FlexibleArrayTy &&
            FlexibleArrayTy->getNumElements() == 0 && Zero && Zero->isZero() &&
            One && One->isOne();
      }

      if (IsPayloadSelector) {
        if (ElementTy)
          return nullptr;
        ElementTy = FlexibleArrayTy->getElementType();
        for (const GEPOperator *Descendant : DescendantGEPs) {
          Type *IndexedTy = Descendant->getSourceElementType();
          if (IndexedTy != ElementTy && !IndexedTy->isIntegerTy(8))
            return nullptr;
        }
      } else if (!ElementTy) {
        DescendantGEPs.push_back(GEP);
      }

      Current = GEP->getPointerOperand();
    }
    return ElementTy;
  }

  bool isPrimitiveArrayPayloadTransfer(Value *Dst, Value *Src) {
    Type *DstElementTy = getUniqueArrayLayoutElementType(Dst);
    Type *SrcElementTy = getUniqueArrayLayoutElementType(Src);
    if (!DstElementTy || !SrcElementTy)
      return false;
    return !containsGCPtrType(DstElementTy) &&
           !containsGCPtrType(SrcElementTy);
  }

  bool isAggregateRegionAnchor(Type *Ty) {
    return Ty && (isa<StructType>(Ty) || isa<ArrayType>(Ty));
  }

  bool isAllowedRegionOuterCast(Type *SrcTy, Type *DstTy) {
    auto *SrcPtrTy = dyn_cast<PointerType>(SrcTy);
    auto *DstPtrTy = dyn_cast<PointerType>(DstTy);
    if (!SrcPtrTy || !DstPtrTy || SrcPtrTy->isOpaque() ||
        DstPtrTy->isOpaque())
      return false;
    Type *SrcElementTy = SrcPtrTy->getNonOpaquePointerElementType();
    Type *DstElementTy = DstPtrTy->getNonOpaquePointerElementType();
    return SrcElementTy == DstElementTy || SrcElementTy->isIntegerTy(8) ||
           DstElementTy->isIntegerTy(8);
  }

  bool isCanonicalHeapBaseArgument(Value *Base) {
    auto *BaseArg = dyn_cast<Argument>(Base);
    if (!BaseArg || BaseArg->getType() != Type::getInt8PtrTy(C, 1))
      return false;
    Function *Parent = BaseArg->getParent();
    bool HasSRet = Parent->arg_size() != 0 &&
                   Parent->getAttributes()
                       .getParamAttrs(0)
                       .hasAttribute(Attribute::StructRet);
    unsigned ThisIndex = HasSRet ? 1 : 0;
    return !Parent->hasFnAttribute("record_mut") ||
           BaseArg->getArgNo() != ThisIndex;
  }

  // A stripped pointer may describe an object layout only when it still
  // terminates at a declaration root. SSA producers such as load/call/phi
  // carry a pointee type, but that type is not an object declaration.
  bool isTrustedDeclarationRoot(Value *Base) {
    return isa<AllocaInst>(Base) || isa<Argument>(Base) ||
           isa<GlobalVariable>(Base);
  }

  IntrinsicInst *getKnownHeapAllocation(Value *Base,
                                        StructType *&LayoutTy) {
    LayoutTy = nullptr;
    auto *Allocation = dyn_cast<IntrinsicInst>(Base);
    if (!Allocation)
      return nullptr;
    switch (Allocation->getIntrinsicID()) {
    case Intrinsic::cj_malloc_object:
    case Intrinsic::cj_malloc_array:
      break;
    default:
      return nullptr;
    }
    auto *TI = dyn_cast<GlobalVariable>(
        Allocation->getArgOperand(0)->stripPointerCasts());
    LayoutTy = TI ? getTypeLayoutType(TI) : nullptr;
    return LayoutTy ? Allocation : nullptr;
  }

  // Return the declared payload layout from either of the canonical AS1
  // object forms already used by the verifier:
  //
  //   i8 addrspace(1)* argument -> %Layout addrspace(1)*
  //
  // or the ABI payload form accepted by classifyTypedHeapPayload:
  //
  //   argument -> i8* addrspace(1)* -> gep 1 -> %Layout addrspace(1)*
  //
  // The typed cast is the declaration boundary for an otherwise erased ABI
  // carrier.  A cast from one typed aggregate pointer to another is not such
  // a boundary and therefore cannot manufacture a root layout.
  Type *getCanonicalTypedHeapRootType(Value *Root) {
    auto *TypedCast = dyn_cast<BitCastOperator>(Root);
    if (!TypedCast)
      return nullptr;
    auto *TypedPtrTy = dyn_cast<PointerType>(TypedCast->getType());
    if (!TypedPtrTy || TypedPtrTy->getAddressSpace() != 1 ||
        TypedPtrTy->isOpaque())
      return nullptr;
    Type *RootTy = TypedPtrTy->getNonOpaquePointerElementType();
    if (!isAggregateRegionAnchor(RootTy))
      return nullptr;

    Value *Carrier = TypedCast->getOperand(0);
    if (isCanonicalHeapBaseArgument(Carrier))
      return RootTy;

    auto *HeaderGEP = dyn_cast<GEPOperator>(Carrier);
    if (!HeaderGEP || HeaderGEP->getNumIndices() != 1 ||
        HeaderGEP->getSourceElementType() != Type::getInt8PtrTy(C) ||
        HeaderGEP->getPointerAddressSpace() != 1)
      return nullptr;
    auto *HeaderIndex = dyn_cast<ConstantInt>(HeaderGEP->idx_begin()->get());
    if (!HeaderIndex || !HeaderIndex->isOne())
      return nullptr;

    auto *BaseCast = dyn_cast<BitCastOperator>(HeaderGEP->getPointerOperand());
    if (!BaseCast || BaseCast->getSrcTy() != Type::getInt8PtrTy(C, 1) ||
        BaseCast->getDestTy() !=
            PointerType::get(Type::getInt8PtrTy(C), 1))
      return nullptr;
    Value *Base = BaseCast->getOperand(0);
    if (!isCanonicalHeapBaseArgument(Base)) {
      StructType *AllocationLayoutTy = nullptr;
      if (!getKnownHeapAllocation(Base, AllocationLayoutTy) ||
          AllocationLayoutTy != RootTy)
        return nullptr;
    }
    return RootTy;
  }

  // Return the statically selected region type.  The leading pointer index
  // must be zero; all remaining indices must be constant, in-bounds struct or
  // array selections.  Scalar/i8 pointer arithmetic is deliberately not a
  // typed-region proof.
  Type *getConstantTypedRegionGEPResultType(const GEPOperator *GEP) {
    Type *CurrentTy = GEP->getSourceElementType();
    if (GEP->getNumIndices() == 0)
      return nullptr;

    auto Index = GEP->idx_begin();
    auto *RootIndex = dyn_cast<ConstantInt>(Index->get());
    if (!RootIndex || !RootIndex->isZero())
      return nullptr;
    // A zero-only GEP preserves an AS0 declaration, including a scalar one.
    // Any actual subobject selection below must walk aggregate types.
    if (++Index == GEP->idx_end())
      return CurrentTy;

    for (; Index != GEP->idx_end(); ++Index) {
      auto *FieldIndex = dyn_cast<ConstantInt>(Index->get());
      if (!FieldIndex || FieldIndex->isNegative() ||
          FieldIndex->getValue().getActiveBits() > 64)
        return nullptr;
      uint64_t Field = FieldIndex->getZExtValue();
      if (auto *ST = dyn_cast<StructType>(CurrentTy)) {
        if (Field >= ST->getNumElements())
          return nullptr;
        CurrentTy = ST->getElementType(Field);
        continue;
      }
      if (auto *AT = dyn_cast<ArrayType>(CurrentTy)) {
        if (Field >= AT->getNumElements())
          return nullptr;
        CurrentTy = AT->getElementType();
        continue;
      }
      return nullptr;
    }
    return CurrentTy;
  }

  Type *recoverCompleteTypedRegionType(Value *Ptr, Value *SizeValue) {
    auto *CopySize = dyn_cast<ConstantInt>(SizeValue);
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    if (!CopySize || !PtrTy || PtrTy->isOpaque())
      return nullptr;

    Value *Current = Ptr;
    // Casts may adapt the final selected pointer to the intrinsic carrier,
    // but may not change one typed aggregate declaration into another.
    while (!getCanonicalTypedHeapRootType(Current)) {
      if (auto *Cast = dyn_cast<BitCastOperator>(Current)) {
        if (!isAllowedRegionOuterCast(Cast->getSrcTy(), Cast->getDestTy()))
          return nullptr;
        Current = Cast->getOperand(0);
        continue;
      }
      if (auto *Cast = dyn_cast<AddrSpaceCastOperator>(Current)) {
        if (!isAllowedRegionOuterCast(Cast->getOperand(0)->getType(),
                                      Cast->getType()))
          return nullptr;
        Current = Cast->getOperand(0);
        continue;
      }
      break;
    }

    Type *RegionTy = nullptr;
    Type *ExpectedRootTy = nullptr;
    while (auto *GEP = dyn_cast<GEPOperator>(Current)) {
      Type *SelectedTy = getConstantTypedRegionGEPResultType(GEP);
      if (!SelectedTy || (ExpectedRootTy && SelectedTy != ExpectedRootTy))
        return nullptr;
      if (!RegionTy)
        RegionTy = SelectedTy;
      ExpectedRootTy = GEP->getSourceElementType();
      Current = GEP->getPointerOperand();
      // Any ordinary cast here lies between the declaration root and a GEP.
      // Only the canonical erased-AS1 declaration boundary is admissible.
      if ((isa<BitCastOperator>(Current) ||
           isa<AddrSpaceCastOperator>(Current)) &&
          !getCanonicalTypedHeapRootType(Current))
        return nullptr;
    }

    Type *RootTy = getCanonicalTypedHeapRootType(Current);
    bool IsAS0Declaration = false;
    if (!RootTy) {
      auto *RootPtrTy = dyn_cast<PointerType>(Current->getType());
      if (!RootPtrTy || RootPtrTy->isOpaque())
        return nullptr;
      if (auto *AI = dyn_cast<AllocaInst>(Current)) {
        if (RootPtrTy->getAddressSpace() != 0)
          return nullptr;
        RootTy = AI->getAllocatedType();
        IsAS0Declaration = true;
      } else if (isa<Argument>(Current) || isa<GlobalVariable>(Current)) {
        if (RootPtrTy->getAddressSpace() == 0) {
          RootTy = RootPtrTy->getNonOpaquePointerElementType();
          IsAS0Declaration = true;
        }
      }
    }

    if (!RootTy || !RootTy->isSized() ||
        (IsAS0Declaration
             ? !RootTy->isFirstClassType()
             : !isAggregateRegionAnchor(RootTy)) ||
        (ExpectedRootTy && ExpectedRootTy != RootTy))
      return nullptr;
    if (!RegionTy)
      RegionTy = RootTy;
    if (!RegionTy->isSized())
      return nullptr;
    TypeSize RegionSize = DL.getTypeAllocSize(RegionTy);
    if (RegionSize.isScalable() ||
        CopySize->getZExtValue() != RegionSize.getFixedSize())
      return nullptr;
    return RegionTy;
  }

  bool isNativeByteArgumentDestination(Value *Ptr) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    if (!PtrTy || PtrTy->getAddressSpace() != 0 || PtrTy->isOpaque() ||
        !PtrTy->getNonOpaquePointerElementType()->isIntegerTy(8))
      return false;
    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *Arg = dyn_cast<Argument>(Base);
    if (!Arg)
      return false;
    auto *BaseTy = dyn_cast<PointerType>(Arg->getType());
    return BaseTy && BaseTy->getAddressSpace() == 0 && !BaseTy->isOpaque() &&
           BaseTy->getNonOpaquePointerElementType()->isIntegerTy(8);
  }

  // Byte arrays have no static field types; they may be erased managed
  // payload and cannot be admitted from layout alone.  A lone i8 field in
  // a multi-field record is a typed UInt8 slot, not this case.
  bool containsErasedI8Array(Type *T) {
    if (!T)
      return false;
    if (auto *AT = dyn_cast<ArrayType>(T)) {
      Type *Elt = AT->getElementType();
      if (Elt->isIntegerTy(8))
        return true;
      return containsErasedI8Array(Elt);
    }
    if (auto *ST = dyn_cast<StructType>(T)) {
      if (ST->isOpaque())
        return false;
      for (Type *Elt : ST->elements()) {
        if (containsErasedI8Array(Elt))
          return true;
      }
    }
    if (auto *VT = dyn_cast<VectorType>(T))
      return containsErasedI8Array(VT->getElementType());
    return false;
  }

  // Field-carrier admission for AS1→AS0 memcpy of a complete LLVM layout
  // that recursively contains no addrspace(1) pointer.  Managed-reference
  // slots are always i8 addrspace(1)* in CodeGen, so a typed pointee with
  // !containsGCPtrType has no heap-ref slots to heal.  Independent of
  // isNoReferenceMemTransfer: that rule needs a declaration root; this one
  // anchors on the memcpy source bitcast pointee.  Erased i8 / {i8} /
  // opaque / [N x i8] / { [N x i8] } carriers are rejected.
  bool isNoAS1FieldCarrierMemTransfer(const MemTransferInst &Copy) {
    if (Copy.isVolatile())
      return false;
    Value *Dst = Copy.getRawDest();
    Value *Src = Copy.getRawSource();
    auto *CopySize = dyn_cast<ConstantInt>(Copy.getLength());
    if (!CopySize || CopySize->isZero() ||
        CopySize->getValue().getActiveBits() > 64)
      return false;
    auto *DstPtrTy = dyn_cast<PointerType>(Dst->getType());
    auto *SrcPtrTy = dyn_cast<PointerType>(Src->getType());
    if (!DstPtrTy || !SrcPtrTy || DstPtrTy->getAddressSpace() != 0 ||
        SrcPtrTy->getAddressSpace() != 1)
      return false;

    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *DstBase = Dst->stripAndAccumulateConstantOffsets(DL, Offset, true);
    if (!Offset.isZero())
      return false;
    auto *AI = dyn_cast<AllocaInst>(DstBase);
    if (!AI || !AI->isStaticAlloca())
      return false;
    Type *AllocTy = AI->getAllocatedType();
    if (!AllocTy->isSized() || !AllocTy->isFirstClassType())
      return false;
    TypeSize AllocSize = DL.getTypeAllocSize(AllocTy);
    if (AllocSize.isScalable() ||
        AllocSize.getFixedSize() != CopySize->getZExtValue())
      return false;

    auto *SrcCast = dyn_cast<BitCastOperator>(Src);
    if (!SrcCast)
      return false;
    auto *CastSrcPtr = dyn_cast<PointerType>(SrcCast->getSrcTy());
    auto *CastDstPtr = dyn_cast<PointerType>(SrcCast->getDestTy());
    if (!CastSrcPtr || !CastDstPtr || CastSrcPtr->isOpaque() ||
        CastDstPtr->isOpaque() || CastSrcPtr->getAddressSpace() != 1 ||
        CastDstPtr->getAddressSpace() != 1)
      return false;
    if (!CastDstPtr->getNonOpaquePointerElementType()->isIntegerTy(8))
      return false;
    Type *TY = CastSrcPtr->getNonOpaquePointerElementType();
    if (!TY || !TY->isFirstClassType() || !TY->isSized() || TY->isIntegerTy(8))
      return false;
    if (auto *ST = dyn_cast<StructType>(TY)) {
      if (ST->isOpaque())
        return false;
      if (ST->getNumElements() == 1 && ST->getElementType(0)->isIntegerTy(8))
        return false;
    }
    if (containsErasedI8Array(TY))
      return false;
    if (TY != AllocTy)
      return false;
    TypeSize TYSize = DL.getTypeAllocSize(TY);
    if (TYSize.isScalable() ||
        TYSize.getFixedSize() != CopySize->getZExtValue())
      return false;
    if (containsGCPtrType(TY) || containsGCPtrType(AllocTy))
      return false;
    Value *TypedPtr = SrcCast->getOperand(0);
    if (isa<PHINode>(TypedPtr) || isa<SelectInst>(TypedPtr) ||
        isa<IntToPtrInst>(TypedPtr))
      return false;
    return true;
  }

  bool isNoReferenceMemTransfer(Value *Dst, Value *Src, Value *SizeValue) {
    // Recover the exact copied region on both sides before consulting the
    // provenance fallbacks below.  A complete region whose own layout has no
    // managed-reference slots is safe to move regardless of whether its
    // enclosing object is a heap object or an AS0 stack/argument object.
    // Bare AS1 i8 carriers intentionally do not recover here.
    Type *DstRegionTy = recoverCompleteTypedRegionType(Dst, SizeValue);
    Type *SrcRegionTy = recoverCompleteTypedRegionType(Src, SizeValue);
    if (DstRegionTy && SrcRegionTy && !containsGCPtrType(DstRegionTy) &&
        !containsGCPtrType(SrcRegionTy))
      return true;

    // std.core write lowers a proven primitive ArrayLayout byte span into an
    // AS0 native i8* argument with a dynamic size.  Permit only that repeated
    // byte sink; an AS1 bare i8* destination remains Unknown.
    if (!isNativeByteArgumentDestination(Dst))
      return false;
    Type *SrcElementTy = getUniqueArrayLayoutElementType(Src);
    return SrcElementTy && !containsGCPtrType(SrcElementTy);
  }

  // Recover a complete array payload rooted at llvm.cj.malloc.array.  The
  // intrinsic carries the canonical TypeInfo, element count, and element
  // size, while the result points at the object header.  Admit either the
  // complete payload range or one constant-index, whole-element write;
  // interior partial, dynamic, or type-erased ranges remain unknown.
  ReferencePayloadKind classifyCompleteArrayPayload(Value *Ptr,
                                                     Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *CopySize = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || !CopySize)
      return ReferencePayloadKind::Unknown;

    APInt Offset(DL.getIndexSizeInBits(PtrTy->getAddressSpace()), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    StructType *LayoutTy = nullptr;
    auto *Allocation = getKnownHeapAllocation(Base, LayoutTy);
    if (!Allocation ||
        Allocation->getIntrinsicID() != Intrinsic::cj_malloc_array)
      return ReferencePayloadKind::Unknown;

    auto *Length = dyn_cast<ConstantInt>(Allocation->getArgOperand(1));
    auto *ElementSize = dyn_cast<ConstantInt>(Allocation->getArgOperand(2));
    if (!Length || !ElementSize)
      return ReferencePayloadKind::Unknown;

    if (!LayoutTy || !LayoutTy->isSized() || LayoutTy->getNumElements() != 2)
      return ReferencePayloadKind::Unknown;
    auto *FlexibleArrayTy = dyn_cast<ArrayType>(LayoutTy->getElementType(1));
    if (!FlexibleArrayTy || FlexibleArrayTy->getNumElements() != 0)
      return ReferencePayloadKind::Unknown;
    Type *ElementTy = FlexibleArrayTy->getElementType();
    if (!ElementTy->isSized())
      return ReferencePayloadKind::Unknown;
    TypeSize LayoutElementSize = DL.getTypeAllocSize(ElementTy);
    if (LayoutElementSize.isScalable())
      return ReferencePayloadKind::Unknown;

    uint64_t Count = Length->getZExtValue();
    uint64_t Stride = ElementSize->getZExtValue();
    if (Stride != LayoutElementSize.getFixedSize() ||
        (Stride != 0 && Count > UINT64_MAX / Stride))
      return ReferencePayloadKind::Unknown;
    uint64_t PayloadSize = Count * Stride;
    uint64_t Sz = CopySize->getZExtValue();

    if (Offset.isNegative() || Offset.getActiveBits() > 64)
      return ReferencePayloadKind::Unknown;
    uint64_t Begin = Offset.getZExtValue();
    if (Begin < ArrayHeadSize)
      return ReferencePayloadKind::Unknown;
    uint64_t Rel = Begin - ArrayHeadSize;

    bool WholePayload = (Rel == 0 && Sz == PayloadSize);
    uint64_t RefSize =
        DL.getTypeAllocSize(Type::getInt8PtrTy(C, 1)).getFixedSize();
    bool OneElement =
        !WholePayload && Stride != 0 && Stride >= RefSize &&
        !ElementTy->isIntegerTy(8) && Sz == Stride && Rel % Stride == 0 &&
        Rel / Stride < Count;
    if (!WholePayload && !OneElement)
      return ReferencePayloadKind::Unknown;

    return containsGCPtrType(ElementTy)
               ? ReferencePayloadKind::ContainsReference
               : ReferencePayloadKind::NoReference;
  }

  // Stack/runtime roots are plain. A whole-object transfer between two typed
  // non-heap locations therefore needs no heap reference barrier, even when
  // the payload contains managed references. Each side must independently
  // prove: addrspace(0), typed (recoverable layout), offset==0, and
  // size==allocsize. Types need not match.
  Type *getCompleteTypedNonHeapObjectType(Value *Ptr, Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || PtrTy->getAddressSpace() != 0 || !Size)
      return nullptr;

    APInt Offset(DL.getIndexSizeInBits(PtrTy->getAddressSpace()), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *BasePtrTy = dyn_cast<PointerType>(Base->getType());
    if (!BasePtrTy || BasePtrTy->getAddressSpace() != 0 ||
        BasePtrTy->isOpaque() || !Offset.isZero())
      return nullptr;
    if (!isTrustedDeclarationRoot(Base))
      return nullptr;

    Type *PayloadTy = BasePtrTy->getNonOpaquePointerElementType();
    if (!PayloadTy->isSized())
      return nullptr;
    auto AllocSize = DL.getTypeAllocSize(PayloadTy);
    if (AllocSize.isScalable() ||
        Size->getZExtValue() != AllocSize.getFixedSize())
      return nullptr;
    return PayloadTy;
  }

  // Return the type reached by a byte offset through struct fields.  Array
  // steps are intentionally not modelled in this admission path: the
  // statepoint registration contract currently binds entry-block struct
  // allocas, while array descent has no exercised frontend witness here.
  Type *findStructSubObjectType(StructType *ST, uint64_t TargetOffset,
                                Type *Wanted, uint64_t BaseOffset = 0) {
    if (BaseOffset == TargetOffset && ST == Wanted)
      return ST;

    const StructLayout *Layout = DL.getStructLayout(ST);
    for (unsigned I = 0, E = ST->getNumElements(); I != E; ++I) {
      Type *ElementTy = ST->getElementType(I);
      uint64_t ElementOffset = BaseOffset + Layout->getElementOffset(I);
      if (ElementOffset == TargetOffset && ElementTy == Wanted)
        return ElementTy;

      auto *Nested = dyn_cast<StructType>(ElementTy);
      if (!Nested || !ElementTy->isSized())
        continue;
      uint64_t ElementSize = DL.getTypeAllocSize(ElementTy).getFixedSize();
      if (TargetOffset < ElementOffset ||
          TargetOffset >= ElementOffset + ElementSize)
        continue;
      if (Type *Found = findStructSubObjectType(
              Nested, TargetOffset, Wanted, ElementOffset))
        return Found;
    }
    return nullptr;
  }

  bool isRegisteredSubObjectCopy(Value *Dst, Type *SrcCompleteTy,
                                 Value *SizeValue) {
    // Safety contract: CJRewriteStatepoint.cpp::computeStructTypeLayouts must
    // register every recursively nested GC slot in each entry-block struct
    // alloca.  Narrowing that registration surface would silently invalidate
    // this admission predicate; keep its nested-struct lit in that pass.
    if (!SrcCompleteTy || !containsGCPtrType(SrcCompleteTy))
      return false;

    auto *DstPtrTy = dyn_cast<PointerType>(Dst->getType());
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!DstPtrTy || DstPtrTy->getAddressSpace() != 0 || !Size)
      return false;

    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *Base = Dst->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *AI = dyn_cast<AllocaInst>(Base);
    if (!AI || AI->getParent() != &AI->getFunction()->getEntryBlock() ||
        Offset.isNegative() || Offset.getActiveBits() > 64)
      return false;

    auto *Root = dyn_cast<StructType>(AI->getAllocatedType());
    if (!Root)
      return false;

    uint64_t TargetOffset = Offset.getZExtValue();
    Type *DstSubObject =
        findStructSubObjectType(Root, TargetOffset, SrcCompleteTy);
    if (!DstSubObject)
      return false;

    // P4 is implied by T coming from the unmodified :250 helper.  Keep this
    // assertion as a tripwire so a future alternate source of T cannot make
    // the size check silently disappear.
    assert(Size->getZExtValue() ==
               DL.getTypeAllocSize(SrcCompleteTy).getFixedSize() &&
           "registered subobject size must equal helper allocsize");
    return true;
  }

  bool collectGCPointerOffsets(Type *Ty, uint64_t BaseOffset,
                               SmallVectorImpl<uint64_t> &Offsets) {
    if (auto *PT = dyn_cast<PointerType>(Ty)) {
      if (isGCPointerType(PT))
        Offsets.push_back(BaseOffset);
      return true;
    }
    if (auto *ST = dyn_cast<StructType>(Ty)) {
      if (!ST->isSized())
        return false;
      const StructLayout *Layout = DL.getStructLayout(ST);
      for (unsigned I = 0, E = ST->getNumElements(); I != E; ++I) {
        if (!collectGCPointerOffsets(
                ST->getElementType(I),
                BaseOffset + Layout->getElementOffset(I), Offsets))
          return false;
      }
      return true;
    }
    if (auto *AT = dyn_cast<ArrayType>(Ty)) {
      if (!AT->getElementType()->isSized())
        return false;
      uint64_t ElementSize =
          DL.getTypeAllocSize(AT->getElementType()).getFixedSize();
      for (uint64_t I = 0, E = AT->getNumElements(); I != E; ++I) {
        if (!collectGCPointerOffsets(AT->getElementType(),
                                     BaseOffset + I * ElementSize, Offsets))
          return false;
      }
      return true;
    }
    // containsGCPtrType can see vectors, but no field-level byte offset rule
    // exists for them here; fail closed rather than inventing one.
    return !containsGCPtrType(Ty);
  }

  bool hasEqualGCPointerOffsets(Type *DstTy, Type *SrcTy) {
    SmallVector<uint64_t, 8> DstOffsets;
    SmallVector<uint64_t, 8> SrcOffsets;
    if (!collectGCPointerOffsets(DstTy, 0, DstOffsets) ||
        !collectGCPointerOffsets(SrcTy, 0, SrcOffsets))
      return false;
    llvm::sort(DstOffsets);
    llvm::sort(SrcOffsets);
    DstOffsets.erase(std::unique(DstOffsets.begin(), DstOffsets.end()),
                     DstOffsets.end());
    SrcOffsets.erase(std::unique(SrcOffsets.begin(), SrcOffsets.end()),
                     SrcOffsets.end());
    return DstOffsets == SrcOffsets;
  }

  // A source GEP in this admission may only select struct fields.  In
  // particular, the leading pointer index must be zero and no array/vector
  // descent is accepted.  The returned type is the complete subobject named
  // by this GEP.
  Type *getConstantStructGEPResultType(const GEPOperator *GEP) {
    if (GEP->getPointerAddressSpace() != 0 || GEP->getNumIndices() < 2)
      return nullptr;

    Type *CurrentTy = GEP->getSourceElementType();
    auto Index = GEP->idx_begin();
    auto *RootIndex = dyn_cast<ConstantInt>(Index->get());
    if (!RootIndex || !RootIndex->isZero())
      return nullptr;

    for (++Index; Index != GEP->idx_end(); ++Index) {
      auto *ST = dyn_cast<StructType>(CurrentTy);
      auto *FieldIndex = dyn_cast<ConstantInt>(Index->get());
      if (!ST || !FieldIndex || FieldIndex->getValue().getActiveBits() > 32)
        return nullptr;
      uint64_t Field = FieldIndex->getZExtValue();
      if (Field >= ST->getNumElements())
        return nullptr;
      CurrentTy = ST->getElementType(Field);
    }
    return CurrentTy;
  }

  // Match CJRewriteStatepoint.cpp::computeStructTypeLayouts: only a whole,
  // statically sized StructType alloca in the entry block is eligible for
  // structural stack-map registration.
  bool isRegisteredStructAlloca(const AllocaInst *AI) {
    return AI && AI->getParent() == &AI->getFunction()->getEntryBlock() &&
           AI->isStaticAlloca() && !AI->isArrayAllocation() &&
           isa<StructType>(AI->getAllocatedType());
  }

  // Prove the one immutable global source form emitted for String literals.
  // This predicate is deliberately source-only: destination admission remains
  // governed by the registered alloca/sret checks above.
  bool isCanonicalCJStringLiteralSource(Value *Ptr, Value *SizeValue) {
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    if (!Size || !PtrTy || PtrTy->getAddressSpace() != 0)
      return false;

    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *StringGV = dyn_cast<GlobalVariable>(Base);
    if (!StringGV || !Offset.isZero() ||
        !StringGV->hasPrivateLinkage() ||
        !StringGV->isConstant() ||
        !StringGV->hasAttribute("cjstring_literal"))
      return false;

    auto *StringTy = dyn_cast<StructType>(StringGV->getValueType());
    if (!StringTy || !StringTy->hasName() ||
        StringTy->getName() != "record.std.core:String" ||
        StringTy->getNumElements() != 3 ||
        StringTy->getElementType(0) != Type::getInt8PtrTy(C, 1) ||
        !StringTy->getElementType(1)->isIntegerTy(32) ||
        !StringTy->getElementType(2)->isIntegerTy(32) || !StringTy->isSized())
      return false;
    TypeSize StringSize = DL.getTypeAllocSize(StringTy);
    if (StringSize.isScalable() ||
        Size->getZExtValue() != StringSize.getFixedSize())
      return false;

    auto *StringInit = dyn_cast<ConstantStruct>(StringGV->getInitializer());
    if (!StringInit || StringInit->getNumOperands() != 3)
      return false;

    // field 0 = addrspacecast(bitcast(@data AS0) AS1).  No GEP, load, call,
    // or inttoptr can satisfy this exact ConstantExpr chain.
    auto *ASCast = dyn_cast<ConstantExpr>(StringInit->getOperand(0));
    if (!ASCast || ASCast->getOpcode() != Instruction::AddrSpaceCast ||
        ASCast->getType() != Type::getInt8PtrTy(C, 1))
      return false;
    auto *BitCast = dyn_cast<ConstantExpr>(ASCast->getOperand(0));
    if (!BitCast || BitCast->getOpcode() != Instruction::BitCast ||
        BitCast->getType() != Type::getInt8PtrTy(C, 0))
      return false;
    auto *DataGV = dyn_cast<GlobalVariable>(BitCast->getOperand(0));
    if (!DataGV || DataGV->getType()->getAddressSpace() != 0)
      return false;

    auto *OffsetCI = dyn_cast<ConstantInt>(StringInit->getOperand(1));
    auto *LengthCI = dyn_cast<ConstantInt>(StringInit->getOperand(2));
    if (!OffsetCI || !LengthCI || !OffsetCI->getType()->isIntegerTy(32) ||
        !LengthCI->getType()->isIntegerTy(32))
      return false;
    uint64_t SliceOffset = OffsetCI->getZExtValue();
    uint64_t SliceLength = LengthCI->getZExtValue();

    if (!DataGV->hasPrivateLinkage() ||
        !DataGV->isConstant() || !DataGV->hasAttribute("cjstring_data"))
      return false;
    auto *DataTy = dyn_cast<StructType>(DataGV->getValueType());
    if (!DataTy || DataTy->getNumElements() != 3 ||
        DataTy->getElementType(0) != Type::getInt8PtrTy(C, 0) ||
        !DataTy->getElementType(1)->isIntegerTy(64))
      return false;
    auto *BytesTy = dyn_cast<ArrayType>(DataTy->getElementType(2));
    if (!BytesTy || !BytesTy->getElementType()->isIntegerTy(8))
      return false;
    uint64_t ByteCount = BytesTy->getNumElements();
    if (SliceOffset > ByteCount || SliceLength > ByteCount - SliceOffset)
      return false;

    auto *DataInit = dyn_cast<ConstantStruct>(DataGV->getInitializer());
    if (!DataInit || DataInit->getNumOperands() != 3)
      return false;
    auto *HeaderLen = dyn_cast<ConstantInt>(DataInit->getOperand(1));
    if (!HeaderLen || HeaderLen->getZExtValue() != ByteCount)
      return false;

    // The header must be the compiler's RawArray<UInt8> type-info global.  Its
    // concrete TypeInfo shape plus RelatedType metadata bind the type contract;
    // the symbol spelling is intentionally not used as the proof.
    auto *HeaderCast = dyn_cast<ConstantExpr>(DataInit->getOperand(0));
    if (!HeaderCast || HeaderCast->getOpcode() != Instruction::BitCast ||
        HeaderCast->getType() != Type::getInt8PtrTy(C, 0))
      return false;
    auto *HeaderGV = dyn_cast<GlobalVariable>(HeaderCast->getOperand(0));
    if (!HeaderGV)
      return false;
    auto *HeaderTy = dyn_cast<StructType>(HeaderGV->getValueType());
    if (!HeaderTy || HeaderTy->getNumElements() != 18)
      return false;
    const MDNode *Related = HeaderGV->getMetadata("RelatedType");
    if (!Related || Related->getNumOperands() != 1)
      return false;
    auto *RelatedName = dyn_cast<MDString>(Related->getOperand(0));
    return RelatedName && RelatedName->getString() == "ArrayLayout.UInt8";
  }

  // Cangjie lowers a known-size aggregate value through an AS0 pointer.  The
  // caller owns the typed stack slot and keeps it in struct-live at the call;
  // the callee only sees this forwarding Argument.  Exclude every native ABI
  // boundary and indirect-result/indirect-input spelling, for which no such
  // owner contract exists.
  bool isABIForwardedAggregateArgument(const Argument *Arg) {
    if (!Arg || !Arg->hasNoAliasAttr() || Arg->hasStructRetAttr() ||
        Arg->hasByValAttr())
      return false;

    const Function *F = Arg->getParent();
    if (!F || !F->hasCangjieGC() || F->hasFnAttribute("cfunc") ||
        F->hasFnAttribute("c2cj") || F->hasFnAttribute("cj2c") ||
        F->hasFnAttribute("pkg_c_wrapper") || F->hasFnAttribute("cjstub"))
      return false;

    auto *PtrTy = dyn_cast<PointerType>(Arg->getType());
    return PtrTy && PtrTy->getAddressSpace() == 0 && !PtrTy->isOpaque() &&
           isa<StructType>(PtrTy->getNonOpaquePointerElementType());
  }

  // A Cangjie sret Argument names caller-owned typed storage.  The caller keeps
  // that result slot live across the call so it can consume the returned value;
  // unlike a regular destination Argument, this is an ABI-visible root owner.
  bool isABIForwardedSRetArgument(const Argument *Arg) {
    if (!Arg || !Arg->hasNoAliasAttr() || !Arg->hasStructRetAttr() ||
        Arg->hasByValAttr())
      return false;

    const Function *F = Arg->getParent();
    if (!F || !F->hasCangjieGC() || F->hasFnAttribute("cfunc") ||
        F->hasFnAttribute("c2cj") || F->hasFnAttribute("cj2c") ||
        F->hasFnAttribute("pkg_c_wrapper") || F->hasFnAttribute("cjstub"))
      return false;

    auto *PtrTy = dyn_cast<PointerType>(Arg->getType());
    return PtrTy && PtrTy->getAddressSpace() == 0 && !PtrTy->isOpaque() &&
           isa<StructType>(PtrTy->getNonOpaquePointerElementType());
  }

  // Recover a complete whole object forwarded by the Cangjie aggregate-value
  // ABI.  This is source-only; destinations must be roots registered in the
  // current frame.
  Type *getCompleteTypedABIForwardedObjectType(Value *Ptr,
                                               Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || PtrTy->getAddressSpace() != 0 || !Size || Size->isZero())
      return nullptr;

    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *Arg = dyn_cast<Argument>(Base);
    if (!isABIForwardedAggregateArgument(Arg) || !Offset.isZero())
      return nullptr;

    Type *RootTy = cast<PointerType>(Arg->getType())
                       ->getNonOpaquePointerElementType();
    if (!RootTy->isSized())
      return nullptr;
    TypeSize RootSize = DL.getTypeAllocSize(RootTy);
    if (RootSize.isScalable() ||
        Size->getZExtValue() != RootSize.getFixedSize())
      return nullptr;
    return RootTy;
  }

  // Recover a complete caller-owned result object from the callee's sret
  // destination.  Sources retain their independent registered-root or Cangjie
  // aggregate-value ABI requirement at the call site.
  Type *getCompleteTypedABISRetObjectType(Value *Ptr, Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || PtrTy->getAddressSpace() != 0 || !Size || Size->isZero())
      return nullptr;

    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *Arg = dyn_cast<Argument>(Base);
    if (!isABIForwardedSRetArgument(Arg) || !Offset.isZero())
      return nullptr;

    Type *RootTy = cast<PointerType>(Arg->getType())
                       ->getNonOpaquePointerElementType();
    if (!RootTy->isSized())
      return nullptr;
    TypeSize RootSize = DL.getTypeAllocSize(RootTy);
    if (RootSize.isScalable() ||
        Size->getZExtValue() != RootSize.getFixedSize())
      return nullptr;
    return RootTy;
  }

  // Recover a complete struct subobject rooted directly in a registered typed
  // AS0 alloca or, when explicitly enabled for the source side, a Cangjie ABI
  // forwarding Argument.  Casts after the field selection may adapt the value
  // to the intrinsic's i8 carrier; casts between the root and a GEP are
  // rejected so a type-punning cast cannot manufacture enclosing provenance.
  Type *getCompleteTypedStructSubObjectType(
      Value *Ptr, Value *SizeValue, bool AllowABIForwardedArgument = false) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || PtrTy->getAddressSpace() != 0 || !Size || Size->isZero())
      return nullptr;

    Value *Current = Ptr;
    Type *SubObjectTy = nullptr;
    Type *EnclosingTy = nullptr;
    bool SawStructGEP = false;
    while (true) {
      if (auto *Cast = dyn_cast<BitCastOperator>(Current)) {
        if (SawStructGEP)
          return nullptr;
        Current = Cast->getOperand(0);
        continue;
      }

      auto *GEP = dyn_cast<GEPOperator>(Current);
      if (!GEP)
        break;
      Type *SelectedTy = getConstantStructGEPResultType(GEP);
      if (!SelectedTy)
        return nullptr;
      if (!SubObjectTy)
        SubObjectTy = SelectedTy;
      EnclosingTy = GEP->getSourceElementType();
      SawStructGEP = true;
      Current = GEP->getPointerOperand();
    }

    auto *AI = dyn_cast<AllocaInst>(Current);
    auto *Arg = dyn_cast<Argument>(Current);
    if (!SawStructGEP ||
        (!isRegisteredStructAlloca(AI) &&
         !(AllowABIForwardedArgument &&
           isABIForwardedAggregateArgument(Arg))))
      return nullptr;
    auto *RootPtrTy = dyn_cast<PointerType>(Current->getType());
    if (!RootPtrTy || RootPtrTy->getAddressSpace() != 0 ||
        RootPtrTy->isOpaque() || !isa<StructType>(SubObjectTy) ||
        !SubObjectTy->isSized())
      return nullptr;
    Type *RootTy = AI ? AI->getAllocatedType()
                      : RootPtrTy->getNonOpaquePointerElementType();
    if (RootTy != EnclosingTy || !isa<StructType>(RootTy))
      return nullptr;

    TypeSize SubObjectSize = DL.getTypeAllocSize(SubObjectTy);
    if (SubObjectSize.isScalable() ||
        Size->getZExtValue() != SubObjectSize.getFixedSize())
      return nullptr;
    return SubObjectTy;
  }

  // The destination surface intentionally matches
  // CJRewriteStatepoint.cpp::computeStructTypeLayouts: one whole, statically
  // sized StructType alloca in the entry block.  Liveness remains a per-
  // statepoint decision in CJGCLiveAnalysis; this only proves registration
  // eligibility when the destination is live.
  Type *getRegisteredWholeObjectType(Value *Ptr, Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!PtrTy || PtrTy->getAddressSpace() != 0 || !Size || Size->isZero())
      return nullptr;

    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    auto *AI = dyn_cast<AllocaInst>(Base);
    if (!isRegisteredStructAlloca(AI) || !Offset.isZero())
      return nullptr;

    auto *Root = cast<StructType>(AI->getAllocatedType());
    if (!Root->isSized() || !containsGCPtrType(Root))
      return nullptr;
    TypeSize RootSize = DL.getTypeAllocSize(Root);
    if (RootSize.isScalable() ||
        Size->getZExtValue() != RootSize.getFixedSize())
      return nullptr;
    return Root;
  }

  bool isRegisteredWholeObjectMirrorCopy(Value *Dst, Value *Src,
                                         Value *SizeValue) {
    Type *SrcSubObjectTy =
        getCompleteTypedStructSubObjectType(Src, SizeValue, true);
    Type *DstRootTy = getRegisteredWholeObjectType(Dst, SizeValue);
    return SrcSubObjectTy && DstRootTy &&
           containsGCPtrType(SrcSubObjectTy) &&
           hasEqualGCPointerOffsets(DstRootTy, SrcSubObjectTy);
  }

  // Static destinations carrying managed references require the typed static
  // barrier path.  Plain static data (no GC slots) remains on the memcpy path.
  bool isGlobalGCPointerDestination(Value *Dst, Type *DstCompleteTy) {
    if (!containsGCPtrType(DstCompleteTy))
      return false;
    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *Base = Dst->stripAndAccumulateConstantOffsets(DL, Offset, true);
    return Offset.isZero() && isa<GlobalVariable>(Base);
  }

  // A bare memtransfer is legal only when typed provenance and a constant,
  // in-bounds range prove the copied bytes contain no managed references.
  // Type erasure, dynamic sizes, and ranges outside the recovered layout are
  // unknown and therefore rejected by the caller.
  ReferencePayloadKind classifyReferencePayload(Value *Ptr, Value *SizeValue) {
    auto *PtrTy = dyn_cast<PointerType>(Ptr->getType());
    if (!PtrTy)
      return ReferencePayloadKind::Unknown;

    auto *Size = dyn_cast<ConstantInt>(SizeValue);
    if (!Size)
      return ReferencePayloadKind::Unknown;

    APInt Offset(DL.getIndexSizeInBits(PtrTy->getAddressSpace()), 0);
    Value *Base = nullptr;
    // Constant addrspacecasts, as emitted for static primitive arrays, are
    // inspected before the generic offset stripper.  The generic helper can
    // otherwise consume both the cast and its source GEP, losing the fact that
    // the frontend cast an interior address.  Only a zero-offset source is a
    // complete typed provenance anchor; dynamic and interior carriers stay
    // fail-closed as Unknown.
    if (auto *Cast = dyn_cast<ConstantExpr>(Ptr);
        Cast && Cast->getOpcode() == Instruction::AddrSpaceCast) {
      APInt SourceOffset(
          DL.getIndexSizeInBits(Cast->getOperand(0)->getType()
                                    ->getPointerAddressSpace()),
          0);
      Value *SourceBase = Cast->getOperand(0)->stripAndAccumulateConstantOffsets(
          DL, SourceOffset, true);
      if (!SourceOffset.isZero())
        return ReferencePayloadKind::Unknown;
      Base = SourceBase;
    } else {
      Base = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    }
    auto *BasePtrTy = dyn_cast<PointerType>(Base->getType());
    if (!BasePtrTy || BasePtrTy->isOpaque())
      return ReferencePayloadKind::Unknown;

    // The type of a pointer produced by a load, call, PHI, select, or
    // inttoptr describes only the SSA value, not the object it designates.
    // Dedicated classifiers above validate supported allocation intrinsics;
    // this structural fallback therefore accepts only declaration roots.
    if (!isTrustedDeclarationRoot(Base))
      return ReferencePayloadKind::Unknown;

    Type *PayloadTy = BasePtrTy->getNonOpaquePointerElementType();
    // A bare i8* (argument, inttoptr, or another erased carrier) describes no
    // enclosing layout. An i8 alloca is still concrete typed storage.
    if (PayloadTy->isIntegerTy(8) && !isa<AllocaInst>(Base))
      return ReferencePayloadKind::Unknown;

    uint64_t CopySize = Size->getZExtValue();
    if (Offset.isNegative() || Offset.getActiveBits() > 64)
      return ReferencePayloadKind::Unknown;

    uint64_t Begin = Offset.getZExtValue();
    uint64_t End = Begin + CopySize;
    if (End < Begin)
      return ReferencePayloadKind::Unknown;

    uint64_t AllocSize = DL.getTypeAllocSize(PayloadTy).getFixedSize();
    if (Begin > AllocSize || End > AllocSize)
      return ReferencePayloadKind::Unknown;
    if (CopySize == 0)
      return ReferencePayloadKind::NoReference;
    if (!containsGCPtrType(PayloadTy))
      return ReferencePayloadKind::NoReference;

    SmallVector<uint64_t, 8> RefPositions;
    if (isGCPointerType(PayloadTy)) {
      RefPositions.push_back(0);
    } else if (auto *ST = dyn_cast<StructType>(PayloadTy)) {
      findReferencePositionInStruct(ST, 0, AllocSize, 0, RefPositions);
    } else if (auto *AT = dyn_cast<ArrayType>(PayloadTy)) {
      findReferencePositionInArray(AT, 0, AllocSize, 0, RefPositions);
    } else {
      // containsGCPtrType() also recognizes vectors.  Until a field-level
      // vector layout rule exists, rejecting the whole typed range is the
      // fail-closed answer.
      return ReferencePayloadKind::ContainsReference;
    }

    uint64_t RefSize = DL.getPointerSize(1);
    bool OverlapsReference = llvm::any_of(
        RefPositions, [Begin, End, RefSize](uint64_t Pos) {
          return Pos < End && Begin < Pos + RefSize;
        });
    return OverlapsReference ? ReferencePayloadKind::ContainsReference
                             : ReferencePayloadKind::NoReference;
  }

  bool findReferencePositions(Value *Ptr, uint64_t Size,
                              SmallVector<uint64_t, 8> &AllRefPos) {
    APInt Offset(DL.getIndexSizeInBits(0), 0);
    Value *PtrBase = Ptr->stripAndAccumulateConstantOffsets(DL, Offset, true);
    if (isGCPointerType(PtrBase->getType())) {
      report_fatal_error("The dst of memcpy base is gc pointer!");
      return true;
    }
    StructType *ST = dyn_cast<StructType>(
        PtrBase->getType()->getNonOpaquePointerElementType());
    if (!ST)
      return false;

    unsigned AllocSize =
        static_cast<unsigned>(DL.getTypeAllocSize(ST).getFixedSize());
    if (AllocSize < Size) {
      report_fatal_error("The memcpy size exceeds allocation size!");
      return false;
    }
    uint64_t BeginPos = Offset.getZExtValue();
    uint64_t EndPos = BeginPos + Size;
    findReferencePositionInStruct(ST, BeginPos, EndPos, 0, AllRefPos);
    return AllRefPos.size() != 0;
  }

  void findReferencePositionInStruct(StructType *ST, uint64_t BeginPos,
                                     uint64_t EndPos, uint64_t CurPos,
                                     SmallVector<uint64_t, 8> &AllRefPos) {
    for (uint64_t i = 0; i < ST->getNumElements(); i++) {
      uint64_t Offset = DL.getStructLayout(ST)->getElementOffset(i) + CurPos;
      Type *EleTy = ST->getElementType(i);
      uint64_t EleSize = DL.getTypeAllocSize(EleTy).getFixedSize();
      if (Offset + EleSize <= BeginPos)
        continue;
      if (Offset >= EndPos)
        return;
      if (isGCPointerType(EleTy)) {
        if (Offset >= BeginPos)
          AllRefPos.push_back(Offset);
      } else if (auto *EST = dyn_cast<StructType>(EleTy)) {
        findReferencePositionInStruct(EST, BeginPos, EndPos, Offset, AllRefPos);
      } else if (auto *EAT = dyn_cast<ArrayType>(EleTy)) {
        findReferencePositionInArray(EAT, BeginPos, EndPos, Offset, AllRefPos);
      }
    }
  }

  void findReferencePositionInArray(ArrayType *AT, uint64_t BeginPos,
                                    uint64_t EndPos, uint64_t CurPos,
                                    SmallVector<uint64_t, 8> &AllRefPos) {
    uint64_t EleNum = AT->getNumElements();
    Type *EleType = AT->getElementType();
    uint64_t EleSize = DL.getTypeAllocSize(EleType).getFixedSize();
    for (uint64_t Idx = 0; Idx < EleNum; Idx++) {
      uint64_t Offset = CurPos + Idx * EleSize;
      if (Offset + EleSize <= BeginPos)
        continue;
      if (Offset >= EndPos)
        return;
      if (isGCPointerType(EleType)) {
        if (Offset >= BeginPos)
          AllRefPos.push_back(Offset);
      } else if (auto *ArrayStruct = dyn_cast<StructType>(EleType)) {
        findReferencePositionInStruct(ArrayStruct, BeginPos, EndPos,
                                      Offset, AllRefPos);
      } else if (auto *NestedArray = dyn_cast<ArrayType>(EleType)) {
        findReferencePositionInArray(NestedArray, BeginPos, EndPos, Offset,
                                     AllRefPos);
      }
    }
  }

  void checkFailed(const Twine &Message, const Value *V) {
    *OS << Message << '\n';
    V->print(*OS, MST);
    *OS << '\n';
    Broken = true;
  }

  void checkFailed(const Twine &Message, const Metadata *MD) {
    *OS << Message << '\n';
    MD->print(*OS, MST, &M);
    *OS << '\n';
    Broken = true;
  }
};

} // namespace

static bool doCJIRVerify(Module &M) {
  Triple T(M.getTargetTriple());
  if (T.isARM())
    return false;
  bool Broken = false;
  CJVerifier CV(M, &dbgs());

  for (GlobalVariable &GV : M.globals()) {
    if (!GV.hasInitializer())
      continue;

    Broken |= CV.verify(GV);
    if (Broken)
      report_fatal_error("Broken global value found, compilation aborted!");
  }

  for (Function &F : M) {
    if (!F.hasCangjieGC())
      continue;

    Broken |= CV.verify(F);
    if (Broken)
      report_fatal_error("Broken function found, compilation aborted!");
  }
  return Broken;
}

PreservedAnalyses CJIRVerifier::run(Module &M, ModuleAnalysisManager &) const {
  if (hasRunCangjieOpt(M)) {
    return PreservedAnalyses::all();
  }
  if (doCJIRVerify(M)) {
    return PreservedAnalyses::none();
  }
  return PreservedAnalyses::all();
}
