//===- CJRuntimeLowering.cpp - CJ Runtime Lowering --------------*- C++ -*-===//
//
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// This pass lowers the functions generated by the cangjie frontend to
// the related runtime.
//
//===----------------------------------------------------------------------===//

#include "llvm/Transforms/Scalar/CJRuntimeLowering.h"

#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/SafepointIRVerifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/CJFillMetadata.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <unordered_map>

using namespace llvm;

namespace llvm {
extern cl::opt<bool> CJLTOOpt;
extern cl::opt<bool> CangjieJIT;
extern cl::opt<bool> CJPipeline;

cl::opt<bool> IVCallInstrEnable("iv-call-instrument-enable", cl::init(false));

cl::opt<std::string> InputFileName("cj-ic-input-file",
                                   cl::desc("Specify the input file"),
                                   cl::value_desc("filename"),
                                   cl::init("./ProfileOutput.txt"));
cl::opt<bool> EnableCJNewArrayFast("enable-cangjie-new-array-fastpath",
                                   cl::init(true), cl::ReallyHidden);
} // namespace llvm

namespace {

const static StringRef ArithmeticExceptionMangleStr =
    "CJ_MCC_ThrowArithmeticException";
const static StringRef C2NStubStr = "CJ_MCC_C2NStub";
const static StringRef N2CStubStr = "CJ_MCC_N2CStub";
const static StringRef FinalizerStr = "CJ_MCC_OnFinalizerCreated";

struct RuntimeLoweringInfo {
  StringRef Name;
  bool SafepointCapable;
};

template <typename KeyT, typename ValT>
using StdMap = std::unordered_map<KeyT, ValT>;
const static StdMap<unsigned, RuntimeLoweringInfo> RuntimeMap {
    {Intrinsic::cj_invoke_gc, {"CJ_MCC_InvokeGC", true}},
    {Intrinsic::cj_get_obj_klass, {"CJ_MCC_GetObjClass", false}},
    {Intrinsic::cj_malloc_object, {"CJ_MCC_NewObject", true}},
    // malloc.array selects one of the CJ_MCC_NewArray* entry points in
    // getMallocArrayFuncName; keep its safepoint classification in this same
    // table even though its callee name is shape-dependent.
    {Intrinsic::cj_malloc_array, {"", true}},
    {Intrinsic::cj_alloca_generic, {"CJ_MCC_NewObject", true}},
    {Intrinsic::cj_malloc_array_generic, {"CJ_MCC_NewArrayGeneric", true}},
    {Intrinsic::cj_division_check_sdiv,
     {"CJ_MCC_ThrowArithmeticException", true}},
    {Intrinsic::cj_division_check_udiv,
     {"CJ_MCC_ThrowArithmeticException", true}},
    {Intrinsic::cj_division_check_srem,
     {"CJ_MCC_ThrowArithmeticException", true}},
    {Intrinsic::cj_division_check_urem,
     {"CJ_MCC_ThrowArithmeticException", true}},
    {Intrinsic::cj_get_vtable_func, {"CJ_MCC_UpdateVMT", false}},
    {Intrinsic::cj_get_mtable_func, {"CJ_MCC_GetMTable", false}},
    {Intrinsic::cj_get_method_outertype, {"CJ_MCC_GetMethodOuterTI", false}},
    {Intrinsic::cj_acquire_rawdata, {"CJ_MCC_AcquireRawData", false}},
    {Intrinsic::cj_release_rawdata, {"CJ_MCC_ReleaseRawData", false}},
    {Intrinsic::cj_post_throw_exception, {"CJ_MCC_PostThrowException", false}},
    {Intrinsic::cj_throw_exception, {"CJ_MCC_ThrowException", true}},
    {Intrinsic::cj_fill_in_stack_trace, {"CJ_MCC_FillInStackTrace", true}},
    {Intrinsic::cj_pre_initialize_package,
     {"CJ_MRT_PreInitializePackage", false}},
    {Intrinsic::cj_get_exception_wrapper, {"CJ_MCC_GetExceptionWrapper", false}},
    {Intrinsic::cj_get_exception_typeid, {"CJ_MC_CGetExceptionTypeID", false}},
    {Intrinsic::cj_set_gc_threshold, {"CJ_MCC_SetGCThreshold", false}},
    {Intrinsic::cj_get_real_heap_size, {"CJ_MCC_GetRealHeapSize", false}},
    {Intrinsic::cj_get_allocated_heap_size,
     {"CJ_MCC_GetAllocatedHeapSize", false}},
    {Intrinsic::cj_get_max_heap_size, {"CJ_MCC_GetMaxHeapSize", false}},
    {Intrinsic::cj_dump_heap_data, {"CJ_MCC_DumpCJHeapData", false}},
    {Intrinsic::cj_get_thread_number, {"CJ_MCC_GetCJThreadNumber", false}},
    {Intrinsic::cj_get_blocking_thread_number,
     {"CJ_MCC_GetBlockingCJThreadNumber", false}},
    {Intrinsic::cj_get_native_thread_number,
     {"CJ_MCC_GetNativeThreadNumber", false}},
    {Intrinsic::cj_get_gc_count, {"CJ_MCC_GetGCCount", false}},
    {Intrinsic::cj_get_gc_time_us, {"CJ_MCC_GetGCTimeUs", false}},
    {Intrinsic::cj_get_gc_freed_size, {"CJ_MCC_GetGCFreedSize", false}},
    {Intrinsic::cj_start_cpu_profiling,
     {"CJ_MCC_StartCpuProfiling", false}},
    {Intrinsic::cj_stop_cpu_profiling,
     {"CJ_MCC_StopCpuProfiling", false}},
    {Intrinsic::cj_register_implicit_exception_raisers,
     {"CJ_MCC_RegisterImplicitExceptionRaisers", false}},
    {Intrinsic::cj_get_type_info, {"CJ_MCC_GetOrCreateTypeInfo", false}},
    {Intrinsic::cj_is_subtype, {"CJ_MCC_IsSubType", false}},
    {Intrinsic::cj_is_tupletype_of, {"CJ_MCC_IsTupleTypeOf", false}},
    {Intrinsic::cj_is_typeinfo_equal, {"CJ_MCC_IsTypeInfoEqual", false}},
    {Intrinsic::cj_set_location, {"SetDebugLocation", false}},
    {Intrinsic::cj_cross_access_barrier, {"CJ_MCC_CrossAccessBarrier", true}},
    {Intrinsic::cj_get_exported_ref, {"CJ_MCC_GetExportedRef", true}},
    {Intrinsic::cj_remove_exported_ref, {"CJ_MCC_RemoveExportedRef", true}},
    {Intrinsic::cj_create_export_handle, {"CJ_MCC_CreateExportHandle", true}},
    {Intrinsic::cj_blackhole, {"CJ_LLVM_BlackHole", false}},
    {Intrinsic::cj_get_lambda_addr, {"CJ_MCC_GetJSLambdaAddr", false}}};

struct LowerGetFieldOffset {
  CallBase *CI;
  Value *TI;
  Value *FieldIndex;
  Value *AttachedOffset;
  uint64_t AttachedInt;

  LowerGetFieldOffset(CallBase *CI) : CI(CI) {
    TI = CI->getArgOperand(0);
    FieldIndex = CI->getArgOperand(1);
    AttachedOffset = CI->getArgOperand(2);
    AttachedInt = dyn_cast<ConstantInt>(AttachedOffset)->getZExtValue();
  }

  bool isZeroIndex() {
    if (auto *Index = dyn_cast<ConstantInt>(FieldIndex)) {
      if (Index->getZExtValue() == 0) {
        return true;
      }
    }
    return false;
  }

  // Replace intrinsic i32 @llvm.cj.get.field.offset (i8* TI, i32 i, i32 j)
  // If TI points to a RawArray or VArray type, call getArrayFieldOffset to
  // compute the offset. Otherwise, call getObjectFieldOffset.
  void replaceGetFieldOffset() {
    IRBuilder<> IRB(CI);

    // If the index is 0, the offset is used as the result.
    if (isZeroIndex()) {
      replaceInstWith(CI, IRB.getInt64(AttachedInt));
      return;
    }

    Value *Result = nullptr;
    if (isRawArrayOrVArray(TI)) {
      Result = getArrayFieldOffset(CI, IRB);
    } else {
      Result = getObjectFieldOffset(CI, IRB);
    }
    replaceInstWith(CI, Result);
  }

  // i64 @llvm.cj.get.field.offset (i8* TI, i64 i, i32 j)
  // %TI = bitcast i8* TI to Typeinfo*
  // %Elem.ptr = getelementptr inbounds Typeinfo, Typeinfo* %TI, i32 0, i32 13
  // %Elem = load Typeinfo*, Typeinfo** %TI.element.ptr, align 8
  // %Elem.Kind.ptr = getelementptr inbounds Typeinfo, Typeinfo* %Elem, i32 0,
  // i32 1 %Elem.Kind = load i32, i32* %Kind.ptr, align 8 %IsRef = icmp slt
  // %Kind, 0 %Elem.size.ptr = getelementptr inbounds Typeinfo, Typeinfo* %Elem,
  // i32 0, i32 4 %Elem.size.i32 = load i32, i32* %Elem.size.ptr, align 8
  // %Elem.size.i64 = zext i32 %Elem.size.i32 to i64
  // %Elem.size = select %IsRef, 8, %Elem.size.i64
  // %TI.offset = mul i64 %Elem.size, i64 i
  // %TI.offset = add i64 j, i64 %TI.offset
  Value *getArrayFieldOffset(CallBase *CI, IRBuilder<> &IRB) {
    SmallVector<Value *> Idxs;
    Value *Offset = nullptr;
    StructType *KlassType =
        StructType::getTypeByName(IRB.getContext(), "TypeInfo");
    Value *TICast = IRB.CreateBitCast(TI, KlassType->getPointerTo());

    Idxs.push_back(IRB.getInt32(0));
    Idxs.push_back(IRB.getInt32(CIT_SUPER));
    Value *ElemPtr = IRB.CreateGEP(KlassType, TICast, {Idxs}, "", true);
    Value *Elem = IRB.CreateLoad(KlassType->getPointerTo(), ElemPtr, "");
    Idxs.clear();
    Idxs.push_back(IRB.getInt32(0));
    Idxs.push_back(IRB.getInt32(CIT_TYPE));
    Value *ElemKindPtr = IRB.CreateGEP(KlassType, Elem, {Idxs}, "", true);
    Value *ElemKind = IRB.CreateLoad(IRB.getInt8Ty(), ElemKindPtr);
    Value *IsRef = IRB.CreateICmpSLT(ElemKind, IRB.getInt8(0));
    Idxs.clear();
    Idxs.push_back(IRB.getInt32(0));
    Idxs.push_back(IRB.getInt32(CIT_SIZE));
    Value *ElemSizePtr = IRB.CreateGEP(KlassType, Elem, {Idxs}, "", true);
    Value *ElemSizeI32 = IRB.CreateLoad(IRB.getInt32Ty(), ElemSizePtr);
    Value *ElemSizeI64 = IRB.CreateZExt(ElemSizeI32, IRB.getInt64Ty());
    const Triple TT(CI->getModule()->getTargetTriple());
    Value *ElemSize =
        IRB.CreateSelect(IsRef, TT.isARM() ? IRB.getInt64(4) : IRB.getInt64(8),
                         ElemSizeI64); // 4|8:ref size
    Offset = IRB.CreateMul(ElemSize, FieldIndex);
    return IRB.CreateAdd(Offset, IRB.getInt64(AttachedInt));
  }

  // i64 @llvm.cj.get.field.offset (i8* TI, i64 i, i32 j)
  // %TI = bitcast i8* TI to Typeinfo*
  // %Offsets.ptr = getelementptr inbounds Typeinfo, Typeinfo* %TI, i32 0, i32 9
  // %Offsets = load i32*, i32** %Offsets.ptr, align 8
  // %Offset.ptr = getelementptr inbounds i32, i32* %Offsets, i64 i
  // %Offset = load i32, i32* %Offset.ptr, align 4
  // %Offset = add i64 j, i32 %Offset
  Value *getObjectFieldOffset(CallBase *CI, IRBuilder<> &IRB) {
    Type *I32Ty = IRB.getInt32Ty();
    SmallVector<Value *> Idxs;
    Value *Offset = nullptr;
    StructType *KlassType =
        StructType::getTypeByName(IRB.getContext(), "TypeInfo");
    Value *TICast = IRB.CreateBitCast(TI, KlassType->getPointerTo());
    Idxs.push_back(IRB.getInt32(0));
    Idxs.push_back(IRB.getInt32(CIT_OFFSETS));
    Value *OffsetsPtr = IRB.CreateGEP(KlassType, TICast, {Idxs}, "", true);
    Type *Int32PtrTy = I32Ty->getPointerTo();
    Value *Offsets = IRB.CreateLoad(Int32PtrTy, OffsetsPtr);
    Idxs.clear();
    Idxs.push_back(FieldIndex);
    Value *OffsetPtr = IRB.CreateGEP(I32Ty, Offsets, {Idxs}, "", true);
    Offset = IRB.CreateLoad(I32Ty, OffsetPtr);
    Offset = IRB.CreateZExt(Offset, IRB.getInt64Ty());
    return IRB.CreateAdd(Offset, IRB.getInt64(AttachedInt));
  }

  bool isRawArrayOrVArray(Value *V) {
    CallInst *CI = dyn_cast<CallInst>(V->stripPointerCasts());
    if (!CI || CI->arg_size() != 3) // 3: llvm.cj.get.type.info arg num
      return false;

    auto CE = dyn_cast<ConstantExpr>(CI->getArgOperand(0));
    if (!CE)
      return false;

    auto *TT = dyn_cast<GlobalVariable>(CE->getOperand(0));
    if (TT->getName().equals("VArray.tt") ||
        TT->getName().equals("RawArray.tt"))
      return true;

    return false;
  }

  void replaceInstWith(Instruction *Old, Value *New) {
    if (auto *Inst = dyn_cast<Instruction>(New)) {
      Inst->setDebugLoc(Old->getDebugLoc());
      Inst->takeName(Old);
    }
    Old->replaceAllUsesWith(New);
    Old->eraseFromParent();
  }
};

struct EscapeScope {
  Function &F;
  DenseSet<Value *> Data;

  explicit EscapeScope(Function &F) : F(F) {
    for (Instruction &I : instructions(F)) {
      if (CallBase *CI = dyn_cast<CallBase>(&I)) {
        visitCallBase(CI);
      } else if (StoreInst *SI = dyn_cast<StoreInst>(&I)) {
        visitStoreInst(SI);
      } else if (ReturnInst *RI = dyn_cast<ReturnInst>(&I)) {
        visitReturnInst(RI);
      }
    }
  }

  bool isEscaped(Value *V) { return Data.contains(V); }

  void visitCallBase(CallBase *CI) {
    if (isa<IntrinsicInst>(CI))
      return;

    for (unsigned Idx = 0; Idx < CI->arg_size(); Idx++) {
      if (CI->paramHasAttr(Idx, Attribute::StructRet))
        continue;

      Value *Arg = CI->getArgOperand(Idx);
      if (isGCPtr(Arg))
        Data.insert(Arg->stripPointerCasts());
    }
  }

  void visitStoreInst(StoreInst *SI) {
    Value *V = SI->getValueOperand();
    if (isGCPtr(V))
      Data.insert(V->stripPointerCasts());
  }

  void visitReturnInst(ReturnInst *RI) {
    Value *V = RI->getReturnValue();
    if (V != nullptr && isGCPtr(V))
      Data.insert(V->stripPointerCasts());
  }
};

/// lowering Cangjie intrinsic functions.
class CJIntrinsicLowering {
public:
  explicit CJIntrinsicLowering(Module &M)
      : M(M), C(M.getContext()), DL(M.getDataLayout()) {}

  void replaceWithRuntimeFunc(CallBase *CI, bool GCLeafFunc, bool GCMalloc) {
    CI->setCalledFunction(getOrInsertRuntimeFunc(CI, GCLeafFunc, GCMalloc));
  }

  // cj.heapmalloc.class (i8* bitcast (TypeInfo* @Klass.ti to i8*), i32 size)
  void setHeapMallocSizeAlign(CallBase *CI) {
    auto ConstantSizeAlign = [&](uint64_t Size) {
      Size += ObjectHeadSize;
      Size = (Size + 7) & (~(7)); // 8 bytes alignment
      CI->setArgOperand(1, ConstantInt::get(Type::getInt32Ty(C), Size));
    };
    auto VariableSizeAlign = [&](Value *Size, IRBuilder<> &IRB) {
      auto *V = IRB.CreateAnd(IRB.CreateAdd(Size, IRB.getInt32(15)),
                              IRB.getInt32(~7));
      CI->setArgOperand(1, V);
    };
    auto GetTISizePointer = [this](Value *TI, IRBuilder<> &IRB) -> Value * {
      Type *Ty = TI->getType()->getNonOpaquePointerElementType();
      if (isa<GlobalVariable>(TI) || isa<StructType>(Ty))
        return IRB.CreateInBoundsGEP(Ty, TI,
                                     {IRB.getInt32(0), IRB.getInt32(CIT_SIZE)});
      auto *ST = StructType::getTypeByName(M.getContext(), "TypeInfo");
      if (!ST)
        report_fatal_error("error");
      auto *SL = M.getDataLayout().getStructLayout(ST);
      auto *GEP =
          IRB.CreateGEP(Ty, TI, {IRB.getInt32(SL->getElementOffset(CIT_SIZE))});
      return IRB.CreateBitCast(GEP, IRB.getInt32Ty()->getPointerTo());
    };

    auto *TI = CI->getArgOperand(0)->stripPointerCasts();
    auto *GV = dyn_cast<GlobalVariable>(TI);
    if (CI->hasMetadata("TrustedSize") ||
        (GV && GV->hasAttribute("NotModifiableClass"))) {
          if (auto *SizeVar = dyn_cast<ConstantInt>(CI->getArgOperand(1)))
            return ConstantSizeAlign(SizeVar->getZExtValue());
          if (GV && GV->hasInitializer())
            return ConstantSizeAlign(TypeInfo(GV).getSize());
          IRBuilder<> IRB(CI);
          VariableSizeAlign(CI->getArgOperand(1), IRB);
    }
    IRBuilder<> IRB(CI);
    auto *Ptr = GetTISizePointer(TI, IRB);
    assert(Ptr->getType()->getNonOpaquePointerElementType() ==
           IRB.getInt32Ty());
    auto *LI = dyn_cast<Instruction>(IRB.CreateLoad(IRB.getInt32Ty(), Ptr));
    LI->setMetadata(LLVMContext::MD_invariant_load, MDNode::get(LI->getContext(), {}));
    LI->setDebugLoc(CI->getDebugLoc());
    return VariableSizeAlign(LI, IRB);
  }

  void replaceFixedNewObject(CallBase *&CI) {
    IRBuilder<> Bdr(CI);
    Function *Func = M.getFunction("CJ_MCC_NewPinnedObject");
    if (Func == nullptr) {
      Type *I8Ptr = Bdr.getInt8PtrTy();
      Type *RefPtr = Bdr.getInt8PtrTy(1);
      Type *I32 = Bdr.getInt32Ty();
      Type *I1 = Bdr.getInt1Ty();
      FunctionType *FT = FunctionType::get(RefPtr, {I8Ptr, I32, I1}, false);
      Func = M.declareCJRuntimeFunc("CJ_MCC_NewPinnedObject", FT, false, true);
    }
    CallBase *I = nullptr;
    SmallVector<Value *> Params = {CI->getArgOperand(0), Bdr.getInt32(SyncSize),
                                   Bdr.getInt1(false)};
    if (isa<CallInst>(CI)) {
      I = Bdr.CreateCall(Func, Params);
    } else if (auto II = dyn_cast<InvokeInst>(CI)) {
      I = Bdr.CreateInvoke(Func, II->getNormalDest(), II->getUnwindDest(),
                           Params);
    }
    I->setDebugLoc(CI->getDebugLoc());
    CI->replaceAllUsesWith(I);
    CI->eraseFromParent();
    CI = I;
  }

  void replaceNewFinalizerFunc(CallBase *CI) {
    IRBuilder<> Bdr(CI);
    Function *Func = M.getFunction("CJ_MCC_NewFinalizer");
    if (Func == nullptr) {
      // NewFinalier cannot add "cj-heapmalloc" attribute, because it may
      // call a finalier method when destructor performing.
      Func = M.declareCJRuntimeFunc("CJ_MCC_NewFinalizer",
                                    CI->getFunctionType(), false);
    }
    CI->setCalledFunction(Func);
  }

  void replaceNewWeakRefFunc(CallBase *CI) {
    IRBuilder<> Bdr(CI);
    Function *Func = M.getFunction("CJ_MCC_NewWeakRefObject");
    if (Func == nullptr) {
      Func = M.declareCJRuntimeFunc("CJ_MCC_NewWeakRefObject",
                                    CI->getFunctionType(), false);
    }
    CI->setCalledFunction(Func);
  }

  // llvm.cj.alloca.generic(TypeInfo* ti, i64 size)
  void replaceAllocaGeneric(CallBase *CI, EscapeScope &ES) {
    if (replaceWithAlloca(CI, ES)) {
      return;
    }
    replaceWithRuntimeFunc(CI, false, true);
    CI->addRetAttr(Attribute::NoAlias);
    setMetadata(CI, "new_gen");
  }

  void replaceIsReference(CallBase *CI) {
    IRBuilder<> IRB(CI);
    Value *Arg = CI->getArgOperand(0)->stripPointerCasts();
    if (auto *GV = dyn_cast<GlobalVariable>(Arg)) {
      if (Value *Res = TypeInfo::getReferenceType(GV)) {
        CI->replaceAllUsesWith(Res);
        CI->eraseFromParent();
        return;
      }
    }
    StructType *ST = StructType::getTypeByName(C, "TypeInfo");
    assert(ST && "TypeInfo type doesn't exist!");
    Value *TypePtr = Arg;
    if (Arg->getType()->getNonOpaquePointerElementType() != ST) {
      TypePtr = IRB.CreateBitCast(Arg, ST->getPointerTo());
    }
    SmallVector<Value *> Idxs;
    Idxs.push_back(IRB.getInt32(0));
    Idxs.push_back(IRB.getInt32(CIT_TYPE));
    Value *KindPtr = IRB.CreateGEP(ST, TypePtr, Idxs);
    LoadInst *Kind = IRB.CreateLoad(IRB.getInt8Ty(), KindPtr);
    setMetadata(Kind, "ti_load");
    Value *Ret = IRB.CreateICmpSLT(Kind, IRB.getInt8(0));
    cast<Instruction>(Ret)->setDebugLoc(CI->getDebugLoc());
    CI->replaceAllUsesWith(Ret);
    CI->eraseFromParent();
  }

  // llvm.cj.gcmalloc.array(TypeInfo* @Klass.ti, i64 length, i64 elem.size)
  void replaceNewArray(CallBase *CI) {
    uint64_t Size = 0; // 0 is slowpath, others is fastpath.
    if (EnableCJNewArrayFast && !CangjieJIT) {
      auto *LengthOp = dyn_cast<ConstantInt>(CI->getArgOperand(1));
      auto *ElemSizeOp = dyn_cast<ConstantInt>(CI->getArgOperand(2));
      if (LengthOp && ElemSizeOp) {
        uint64_t ElemSize = ElemSizeOp->getZExtValue();
        if (ElemSize == 0) {
          Size = ArrayHeadSize;
        } else {
          uint64_t Length = LengthOp->getZExtValue();
          // check array size
          if (MaxArrayFast / ElemSize > Length) {
            Size = ArrayHeadSize + ElemSize * Length;
            Size = (Size + 7) & (~(7)); // 8 bytes alignment
          }
        }
      }
    }
    if (Size > 0) {
      CI->setArgOperand(2, ConstantInt::get(Type::getInt64Ty(C), Size));
      setMetadata(CI, "fast_new_array");
    } else {
      CI->setArgOperand(2, PoisonValue::get(Type::getInt64Ty(C)));
    }
    CI->setCalledFunction(getOrInsertRuntimeFunc(CI, false, true));
    return;
  }

  void replaceIsTypeInfoEqual(CallBase *CI) {
    IRBuilder<> IRB(CI);
    Value *Arg0 = CI->getArgOperand(0)->stripPointerCasts();
    Value *Arg1 = CI->getArgOperand(1)->stripPointerCasts();
    StructType *ST = StructType::getTypeByName(C, "TypeInfo");
    assert(ST && "TypeInfo type doesn't exist!");
    Value *TypePtr0 = Arg0;
    if (Arg0->getType()->getNonOpaquePointerElementType() != ST) {
      TypePtr0 = IRB.CreateBitCast(Arg0, ST->getPointerTo());
    }
    Value *TypePtr1 = Arg1;
    if (Arg1->getType()->getNonOpaquePointerElementType() != ST) {
      TypePtr1 = IRB.CreateBitCast(Arg1, ST->getPointerTo());
    }
    SmallVector<Value *> Idxs;
    Idxs.push_back(IRB.getInt32(0));
    Idxs.push_back(IRB.getInt32(CIT_UUID));
    Value *UUID0Ptr = IRB.CreateInBoundsGEP(ST, TypePtr0, Idxs);
    Value *UUID0 = IRB.CreateLoad(IRB.getInt32Ty(), UUID0Ptr);
    Value *UUID1Ptr = IRB.CreateInBoundsGEP(ST, TypePtr1, Idxs);
    Value *UUID1 = IRB.CreateLoad(IRB.getInt32Ty(), UUID1Ptr);
    Value *Ret = IRB.CreateICmpEQ(UUID0, UUID1);
    cast<Instruction>(Ret)->setDebugLoc(CI->getDebugLoc());
    CI->replaceAllUsesWith(Ret);
    CI->eraseFromParent();
  }

  void replaceIsTupleTypeOf(CallBase *CI) {
    IRBuilder<> IRB(CI);
    StringRef Callee = getRuntimeFuncName(CI);
    assert(Callee != "" && "Callee don`t exist.");
    auto Itr = RTFuncMap.find(Callee);
    Function *Func = nullptr;
    if (Itr != RTFuncMap.end()) {
      Func = Itr->second;
    } else {
      Type *boolTy = IRB.getInt1Ty();
      Type *I8Ptr = IRB.getInt8PtrTy();
      FunctionType *FT = FunctionType::get(boolTy, {I8Ptr, I8Ptr, I8Ptr}, false);
      Func = M.declareCJRuntimeFunc(Callee, FT, true, false);
      auto FnAttrs = CI->getCalledFunction()->getAttributes().getFnAttrs();
      auto NewAttrs =
          Func->getAttributes().addFnAttributes(C, AttrBuilder(C, FnAttrs));
      Func->setAttributes(NewAttrs);
      RTFuncMap[Callee] = Func;
    }
    assert(Func != nullptr && "replaceIsTupleTypeOf failed.");
    CI->setCalledFunction(Func);
    if (CI->getArgOperand(0)->getType() == IRB.getInt8PtrTy(1)) {
      auto ObjCast = IRB.CreateAddrSpaceCast(CI->getArgOperand(0), IRB.getInt8PtrTy(0));
      CI->setArgOperand(0, ObjCast);
    }
  }

  // %0 = getelementptr i8, i8* %ti, i32 72
  // %1 = bitcast i8* %0 to i8***
  // %2 = load i8**, i8*** %1
  // %3 = getelementptr i8*, i8** %2, %index_type
  // %4 = load i8*, i8** %3
  // TryUpdateMTable
  // %5 = bitcast i8* %4 to %ExDef*
  // %6 = getelementptr inbounds %ExDef, %ExDef* %5, i64 0, i32 ET_FUNC_TABLE
  // %7 = bitcast i8* %6 to i8***
  // %8 = load i8**, i8*** %7
  // %9 = getelementptr i8*, i8** %8, %index_func
  // %10 = load i8*, i8** %9
  void replaceGetVTableFunc(CallBase *CB) {
    IRBuilder<> IRB(CB);
    auto *TI = CB->getArgOperand(0);
    auto *ST = StructType::getTypeByName(CB->getContext(), "TypeInfo");
    auto *SL = CB->getModule()->getDataLayout().getStructLayout(ST);
    auto VOffset = SL->getElementOffset(CIT_VTABLE);
    auto *GEP0 =
        IRB.CreateGEP(TI->getType()->getNonOpaquePointerElementType(), TI,
                      {ConstantInt::get(IRB.getInt32Ty(), VOffset)});
    auto *BS0 = IRB.CreateBitCast(
        GEP0, IRB.getInt8PtrTy()->getPointerTo()->getPointerTo());
    auto *LI0 =
        IRB.CreateLoad(BS0->getType()->getNonOpaquePointerElementType(), BS0);
    LI0->setMetadata(LLVMContext::MD_virtual_call,
                     MDNode::get(CB->getContext(), {}));
    LI0->setMetadata(LLVMContext::MD_invariant_load,
                     MDNode::get(CB->getContext(), {}));
    auto *GEP1 = IRB.CreateGEP(LI0->getType()->getNonOpaquePointerElementType(),
                               LI0, {CB->getArgOperand(1)});
    auto *LI1 =
        IRB.CreateLoad(GEP1->getType()->getNonOpaquePointerElementType(), GEP1);
    LI1->setMetadata(LLVMContext::MD_invariant_load,
                     MDNode::get(CB->getContext(), {}));

    auto *Int8PtrTy = Type::getInt8PtrTy(C);
    auto *Callee = getOrInsertRuntimeFunc(CB, true, false,
      // CJ_MCC_UpdateVMT: void(*)(i8*, i8*, i8*)
      FunctionType::get(Type::getVoidTy(C), {Int8PtrTy, Int8PtrTy, Int8PtrTy}, false));
    IRB.CreateCall(Callee, {CB->getArgOperand(0), CB->getArgOperand(3), LI1});

    auto *BS1 = IRB.CreateBitCast(
        LI1, StructType::getTypeByName(CB->getContext(), "ExtensionDef")
                 ->getPointerTo());
    auto *GEP2 =
        IRB.CreateGEP(BS1->getType()->getNonOpaquePointerElementType(), BS1,
                      {ConstantInt::get(IRB.getInt64Ty(), 0),
                       ConstantInt::get(IRB.getInt32Ty(), ET_FUNC_TABLE)});
    auto *BS2 = IRB.CreateBitCast(
        GEP2, IRB.getInt8PtrTy()->getPointerTo()->getPointerTo());
    auto *LI2 =
        IRB.CreateLoad(BS2->getType()->getNonOpaquePointerElementType(), BS2);
    LI2->setMetadata(LLVMContext::MD_invariant_load,
                     MDNode::get(CB->getContext(), {}));
    auto *GEP3 = IRB.CreateGEP(LI2->getType()->getNonOpaquePointerElementType(),
                               LI2, {CB->getArgOperand(2)});
    auto *LI3 =
        IRB.CreateLoad(GEP3->getType()->getNonOpaquePointerElementType(), GEP3);
    LI3->setMetadata(LLVMContext::MD_intro_type,
                     CB->getMetadata(LLVMContext::MD_intro_type));
    LI3->setMetadata(LLVMContext::MD_func_table,
                     MDNode::get(CB->getContext(),
                                 {ConstantAsMetadata::get(cast<ConstantInt>(
                                     CB->getArgOperand(2)))}));
    LI3->setMetadata(LLVMContext::MD_invariant_load,
                     MDNode::get(CB->getContext(), {}));
    // Wrap with @llvm.cj.vfe.info to preserve VFE metadata as intrinsic args.
    auto *ObjTypeMD = CB->getMetadata(LLVMContext::MD_obj_type);
    auto *FuncOffset = cast<ConstantInt>(CB->getArgOperand(2));
    Value *Result = LI3;
    if (ObjTypeMD) {
      auto *VFEInfoFn = Intrinsic::getDeclaration(
          CB->getModule(), Intrinsic::cj_vfe_info);
      Result = IRB.CreateCall(VFEInfoFn,
                              {LI3, MetadataAsValue::get(CB->getContext(),
                                                         ObjTypeMD),
                               FuncOffset});
    }
    CB->replaceAllUsesWith(Result);
    CB->eraseFromParent();
  }

  void replaceGetMTableFunc(CallBase *CB) {
    auto &C = CB->getContext();
    auto *Callee = getOrInsertRuntimeFunc(
        CB, true, false,
        // CJ_MCC_GetMTable: i8*(*)(i8*, i8*)
        FunctionType::get(
            Type::getInt8PtrTy(C),
            {CB->getArgOperand(0)->getType(), CB->getArgOperand(1)->getType()},
            false));
    IRBuilder<> IRB(CB);
    auto *Int8PtrTy = Type::getInt8PtrTy(C);
    auto *CI =
        IRB.CreateCall(Callee, {CB->getArgOperand(0), CB->getArgOperand(1)});
    auto *BC0 = IRB.CreateBitCast(CI, Int8PtrTy->getPointerTo());
    auto *GEP = IRB.CreateGEP(Int8PtrTy, BC0, {CB->getArgOperand(2)});
    auto *LI = IRB.CreateLoad(Int8PtrTy, GEP);
    LI->setMetadata(LLVMContext::MD_invariant_load, MDNode::get(C, {}));
    LI->setMetadata(LLVMContext::MD_func_table,
                    MDNode::get(C, {ConstantAsMetadata::get(cast<ConstantInt>(
                                       CB->getArgOperand(2)))}));
    // Wrap with @llvm.cj.vfe.info to preserve VFE metadata as intrinsic args.
    auto *ObjTypeMD = CB->getMetadata(LLVMContext::MD_obj_type);
    auto *FuncOffset = cast<ConstantInt>(CB->getArgOperand(2));
    Value *Result = LI;
    if (ObjTypeMD) {
      auto *VFEInfoFn = Intrinsic::getDeclaration(
          CB->getModule(), Intrinsic::cj_vfe_info);
      Result = IRB.CreateCall(VFEInfoFn,
                              {LI, MetadataAsValue::get(C, ObjTypeMD),
                               FuncOffset});
    }
    CB->replaceAllUsesWith(Result);
    CB->eraseFromParent();
  }

  void replaceGetMethodOuterType(CallBase *CB) {
    auto *Callee = getOrInsertRuntimeFunc(CB, true, false,
      // CJ_MCC_GetMethodOuterType: TypeInfo*(*)(i8*, i8*, i64 index)
      CB->getFunctionType());
    CB->setCalledFunction(Callee);
  }

  void replaceDivisionCheck() {
    if (DivisionChecks.size() == 0)
      return;

    for (unsigned I = 0; I < DivisionChecks.size(); I++) {
      loweringGCDiv(DivisionChecks[I]);
    }
  }

  void finishAll() {
    replaceDivisionCheck();
    DivisionChecks.clear();
  }

  void markLoweringDivisionCheck(CallBase *CI) { DivisionChecks.push_back(CI); }

  bool loweringGCDiv(CallBase *CI) {
    IRBuilder<> Builder(CI);
    Type *TypeOfOperand = CI->getOperand(1)->getType();

    ICmpInst *DivisorCmp =
        new ICmpInst(CI, ICmpInst::ICMP_EQ, CI->getOperand(1),
                     ConstantInt::get(TypeOfOperand, 0), "divisor_is_0");
    Instruction *ThenTerm = nullptr;
    Instruction *ElseTerm = nullptr;
    SplitBlockAndInsertIfThenElse(DivisorCmp, CI, &ThenTerm, &ElseTerm);
    BasicBlock *ThenBB = ThenTerm->getParent();
    BasicBlock *ElseBB = ElseTerm->getParent();
    ThenBB->setName("div.divisorIs0");
    ElseBB->setName("div.divisorIsNot0");
    CI->getParent()->setName("divEnd");

    auto ArithmeticFn = M.getOrInsertFunction(ArithmeticExceptionMangleStr,
                                              Builder.getVoidTy());
    auto *II = dyn_cast<InvokeInst>(CI);
    Instruction *Arithmetic;
    if (II != nullptr) {
      // change invoke @llvm.cj.division.check.XXX(a, b) to:
      // divisor_is_0: icmp eq b, 0
      // br i1 divisor_is_0, label %then, label %else
      // div.divisorIs0:
      //    invoke void MCC_ThrowArithmeticException()
      // div.divisorIsNot0:
      //    br label %1
      // 1:
      //    %0 = sdiv/udiv/srem/urem a, b
      //    br label %NormalDest
      Arithmetic = Builder.CreateInvoke(ArithmeticFn, II->getParent(),
                                        II->getUnwindDest());
      Arithmetic->moveBefore(ThenBB->getTerminator());
      dyn_cast<InvokeInst>(Arithmetic)
          ->getUnwindDest()
          ->replacePhiUsesWith(CI->getParent(), ThenBB);
    } else {
      // change call @llvm.cj.division.check.XXX(a, b) to:
      // divisor_is_0: icmp eq b, 0
      // br i1 divisor_is_0, label %then, label %else
      // div.divisorIs0:
      //    call void MCC_ThrowArithmeticException()
      //    unreachable
      // div.divisorIsNot0:
      //    br label %1
      // 1:
      //    %0 = sdiv/udiv/srem/urem a, b
      Arithmetic = Builder.CreateCall(ArithmeticFn);
      Arithmetic->moveBefore(ThenBB->getTerminator());
      auto Unreach = Builder.CreateUnreachable();
      Unreach->moveAfter(Arithmetic);
    }
    ThenBB->getTerminator()->eraseFromParent();

    Builder.SetInsertPoint(CI);
    Value *NewCI = createGCDiv(Builder, CI);
    if (CI->getOpcode() == Instruction::Invoke) {
      Builder.CreateBr(II->getNormalDest());
    }
    CI->replaceAllUsesWith(NewCI);
    CI->eraseFromParent();
    return true;
  }

  void loweringMallocObject(CallBase *&CI) {
    const MDNode *MD = CI->getMetadata("MallocType");
    if (MD == nullptr) {
      setHeapMallocSizeAlign(CI);
      replaceWithRuntimeFunc(CI, false, true);
    } else {
      StringRef Ty = dyn_cast<MDString>(MD->getOperand(0).get())->getString();
      if (Ty.equals("HasFinalizer")) {
        setHeapMallocSizeAlign(CI);
        replaceNewFinalizerFunc(CI);
      } else if (Ty.equals("Future") || Ty.equals("Mutex") ||
                 Ty.equals("Monitor") || Ty.equals("WaitQueue")) {
        replaceFixedNewObject(CI);
      } else if (Ty.equals("WeakRef")) {
        setHeapMallocSizeAlign(CI);
        replaceNewWeakRefFunc(CI);
      } else {
        setHeapMallocSizeAlign(CI);
        replaceWithRuntimeFunc(CI, false, true);
      }
    }
    CI->addRetAttr(Attribute::NoAlias);
  }

private:
  Module &M;
  LLVMContext &C;
  const DataLayout &DL;
  SmallVector<CallBase *, 8> DivisionChecks;
  // map intrinsic to runtime API function type.
  DenseMap<StringRef, Function *> RTFuncMap;

  StringRef getRuntimeFuncName(CallBase *CI) const {
    Intrinsic::ID IID = CI->getIntrinsicID();
    if (IID == Intrinsic::cj_malloc_array) {
      return getMallocArrayFuncName(CI);
    } else {
      auto Itr = RuntimeMap.find(IID);
      assert(Itr != RuntimeMap.end() && "Runtime function don`t exist.");
      return Itr->second.Name;
    }
  }

  StringRef getMallocArrayFuncName(CallBase *CI) const {
    Value *Arg0 = CI->getOperand(0);
    // gc.malloc.array(i64, bitcast arg1 to i8*)
    auto *CastExpr = dyn_cast<ConstantExpr>(Arg0);
    auto *KlassGV = dyn_cast<GlobalVariable>(CastExpr->getOperand(0));
    TypeInfo ArrayKlass(KlassGV);

    Type *ET = ArrayKlass.getArrayElementType();
    if (ET->isPointerTy()) {
      return "CJ_MCC_NewObjArray";
    } else if (ET->isStructTy() || ET->isArrayTy()) {
      return "CJ_MCC_NewArray";
    } else {
      unsigned Size =
          static_cast<unsigned>(DL.getTypeAllocSize(ET).getFixedSize());
      switch (Size) {
      case 1:
        return "CJ_MCC_NewArray8";
      case 2:
        return "CJ_MCC_NewArray16";
      case 4:
        return "CJ_MCC_NewArray32";
      case 8:
        return "CJ_MCC_NewArray64";
      default:
        break;
      }
    }
    report_fatal_error("Unsupported element klass type for gc.malloc.array!");
    return "";
  }

  Function *getOrInsertRuntimeFunc(CallBase *CI, bool GCLeafFunc, bool GCMalloc,
                                   FunctionType *FuncType = nullptr) {
    StringRef Callee = getRuntimeFuncName(CI);
    assert(Callee != "" && "Callee don`t exist.");
    auto Itr = RTFuncMap.find(Callee);
    if (Itr != RTFuncMap.end()) {
      Function *RTFunc = Itr->second;
      if (!RTFunc->isDeclaration()) {
        RTFunc->deleteBody();
      }
      return RTFunc;
    }

    FunctionType *FT = FuncType ? FuncType : CI->getFunctionType();
    Function *Func = M.declareCJRuntimeFunc(Callee, FT, GCLeafFunc, GCMalloc);
    assert(Func != nullptr && "getOrInsertFunction fail");

    // Transfer the original function's attributes.
    auto FnAttrs = CI->getCalledFunction()->getAttributes().getFnAttrs();
    auto NewAttrs =
        Func->getAttributes().addFnAttributes(C, AttrBuilder(C, FnAttrs));
    Func->setAttributes(NewAttrs);
    if (Func->getName().isSetDebugLocation())
      Func->setUnnamedAddr(GlobalValue::UnnamedAddr::Local);
    RTFuncMap[Callee] = Func;
    if (CI->getIntrinsicID() == Intrinsic::cj_blackhole) {
      Func->addFnAttr(Attribute::ReadOnly);
    }
    return Func;
  }

  // If the size is constant and typeinfo is known in alloca.generic, and
  // this alloca.generic is not escaped, we replace it with a alloca inst.
  bool replaceWithAlloca(CallBase *CI, EscapeScope &ES) {
    if (ES.isEscaped(CI))
      return false;

    auto *SizeOp = dyn_cast<ConstantInt>(CI->getArgOperand(1));
    if (!SizeOp || SizeOp->getZExtValue() > MaxAllocaObj)
      return false;

    Value *TIArg = CI->getArgOperand(0)->stripPointerCasts();
    auto *GV = dyn_cast<GlobalVariable>(TIArg);
    if (!GV)
      return false;

    AllocaInst *AI = nullptr;
    BasicBlock &EntryBB = CI->getFunction()->getEntryBlock();
    Instruction *InsertPos = &*EntryBB.getFirstInsertionPt();
    IRBuilder<> IRB(InsertPos);
    auto *TIType = StructType::getTypeByName(C, "TypeInfo");
    const Triple TT(CI->getModule()->getTargetTriple());
    if (isPrimitiveTypeInfo(GV)) {
      SmallVector<Type *> ElemTypes;
      ElemTypes.push_back(TIType->getPointerTo());
      if (TT.isARM())
        ElemTypes.push_back(IRB.getInt32Ty());
      ElemTypes.push_back(IRB.getInt64Ty());
      AI = IRB.CreateAlloca(StructType::get(C, ElemTypes));
      Value *BC = IRB.CreateBitCast(AI, IRB.getInt8PtrTy()->getPointerTo());
      Value *GVExpr = ConstantExpr::getBitCast(GV, IRB.getInt8PtrTy());
      IRB.SetInsertPoint(CI);
      IRB.CreateStore(GVExpr, BC);
    } else {
      StructType *ST = getTypeLayoutType(GV);
      assert(ST && "alloca.generic layout info missing!");
      SmallVector<Type *> ElemTypes;
      ElemTypes.push_back(TIType->getPointerTo());
      if (TT.isARM())
        ElemTypes.push_back(IRB.getInt32Ty());
      ElemTypes.push_back(ST);
      StructType *AllocaTy = StructType::get(C, ElemTypes);
      AI = IRB.CreateAlloca(AllocaTy);
      Value *BC = IRB.CreateBitCast(AI, IRB.getInt8PtrTy()->getPointerTo());
      Value *GVExpr = ConstantExpr::getBitCast(GV, IRB.getInt8PtrTy());
      IRB.CreateStore(GVExpr, BC);
      const StructLayout *AllocaSL = DL.getStructLayout(AllocaTy);
      // Count the arm32 i32 padding (see ElemTypes above) so the memset
      // starts at the payload @8, not the padding @4.
      uint64_t HeaderSize =
          DL.getTypeAllocSize(TIType->getPointerTo()).getFixedSize() +
          (TT.isARM() ? 4 : 0);
      uint64_t MemSize = AllocaSL->getSizeInBytes() - HeaderSize;
      // %x.payload = getelementptr i8*, %x.i, HeaderSize
      // call @memset(%x.payload, 0, MemSize)
      Value *Data =
          IRB.CreateGEP(IRB.getInt8Ty(), IRB.CreateBitCast(AI, IRB.getInt8PtrTy()),
                        {IRB.getInt32(HeaderSize)});
      IRB.SetInsertPoint(CI);
      IRB.CreateMemSet(Data, IRB.getInt8(0), MemSize, Align(8));
    }
    Value *ASC = IRB.CreateAddrSpaceCast(AI, IRB.getInt8PtrTy(1));
    CI->replaceAllUsesWith(ASC);
    // Set terminator for invoke instruction.
    if (auto *II = dyn_cast<InvokeInst>(CI)) {
      IRB.CreateBr(II->getNormalDest());
    }
    CI->eraseFromParent();
    return true;
  }

  void setMetadata(Instruction *I, StringRef Kind) {
    I->setMetadata(Kind, MDNode::get(C, {}));
  }

  Value *createGCDiv(IRBuilder<> &Builder, const CallBase *CI) const {
    switch (CI->getIntrinsicID()) {
    default:
      report_fatal_error("createGCDiv: Unsupported intrinsic type");
      return nullptr;
    case Intrinsic::cj_division_check_sdiv:
      return Builder.CreateSDiv(CI->getOperand(0), CI->getOperand(1), "Sdiv");
    case Intrinsic::cj_division_check_udiv:
      return Builder.CreateUDiv(CI->getOperand(0), CI->getOperand(1), "Udiv");
    case Intrinsic::cj_division_check_srem:
      return Builder.CreateSRem(CI->getOperand(0), CI->getOperand(1), "Srem");
    case Intrinsic::cj_division_check_urem:
      return Builder.CreateURem(CI->getOperand(0), CI->getOperand(1), "Urem");
    }
  }
};
} // namespace

bool llvm::cjIntrinsicLowersToSafepointCapableCall(Intrinsic::ID ID) {
  auto Runtime = RuntimeMap.find(ID);
  if (Runtime != RuntimeMap.end())
    return Runtime->second.SafepointCapable;
  // Barrier intrinsics are lowered by CJBarrierLowering after
  // PlaceSafepoints/CJRewriteStatepoint.  Their eventual CJ_MCC_* calls are
  // therefore not calls on which RSP inserts a statepoint at this verifier
  // program point; they retain the intrinsic (leaf) policy here.
  return false;
}

static bool isCJBlockingFunc(Function &F) {
  if (CJPipeline && F.getName().equals("system")) {
    return true;
  }
  return false;
}

static void insertGVForNativeFunc(Module &M, Function &F,
                                  const TargetLibraryInfo &TLI) {
  LibFunc LF;
  // For the libc library function, if it is in the trustlist, we do not need
  // to generate C2N Stub for it.

  if (F.hasFnAttribute("cj2c") && TLI.getLibFunc(F, LF)) {
    if (!isCJBlockingFunc(F) && TLI.has(LF)) {
      F.removeFnAttr("cj2c");
      return;
    }
  }
  GlobalVariable *CJFuncGV = cast<GlobalVariable>(
      M.getOrInsertGlobal(F.getName().str() + ".CJStubGV", F.getType()));
  CJFuncGV->setInitializer(&F);
  CJFuncGV->setLinkage(GlobalVariable::InternalLinkage);
  CJFuncGV->addAttribute("cj-native");
}

// Declares MCC functions ready for backend processing.
static void declareRuntimeFunc(Module &M) {
  LLVMContext &C = M.getContext();
  // declare C2NStub and N2CStub
  auto *NativeStubFT = FunctionType::get(Type::getVoidTy(C), true);
  M.declareCJRuntimeFunc(C2NStubStr, NativeStubFT, true);
  M.declareCJRuntimeFunc(N2CStubStr, NativeStubFT, true);

  Type *RefType = Type::getInt8PtrTy(C, 1);
  auto *FinalizerFT = FunctionType::get(RefType, RefType, false);
  M.declareCJRuntimeFunc(FinalizerStr, FinalizerFT, true);
}

static bool runtimeLoweringFunc(Function &F, CJIntrinsicLowering &Lowering) {
  bool Changed = false;
  EscapeScope ES(F);

  for (auto I = inst_begin(F); I != inst_end(F);) {
    Instruction *Inst = &*I++;
    auto *CI = dyn_cast<CallBase>(Inst);
    if (!CI || CI->getCalledFunction() == nullptr) {
      continue;
    }
    unsigned IID = CI->getIntrinsicID();
    switch (IID) {
    default:
      break;
    case Intrinsic::cj_get_field_offset: {
      LowerGetFieldOffset Lower(CI);
      Lower.replaceGetFieldOffset();
      Changed = true;
      break;
    }
    case Intrinsic::cj_is_reference: {
      Lowering.replaceIsReference(CI);
      Changed = true;
      break;
    }
    case Intrinsic::cj_is_typeinfo_equal: {
      Lowering.replaceIsTypeInfoEqual(CI);
      Changed = true;
      break;
    }
    case Intrinsic::cj_is_tupletype_of: {
      Lowering.replaceIsTupleTypeOf(CI);
      Changed = true;
      break;
    }
    case Intrinsic::cj_get_obj_klass:
    case Intrinsic::cj_acquire_rawdata:
    case Intrinsic::cj_release_rawdata:
    case Intrinsic::cj_set_location:
    case Intrinsic::cj_pre_initialize_package:
    case Intrinsic::cj_get_exception_wrapper:
    case Intrinsic::cj_get_exception_typeid:
    case Intrinsic::cj_get_real_heap_size:
    case Intrinsic::cj_get_allocated_heap_size:
    case Intrinsic::cj_get_max_heap_size:
    case Intrinsic::cj_dump_heap_data:
    case Intrinsic::cj_get_thread_number:
    case Intrinsic::cj_get_blocking_thread_number:
    case Intrinsic::cj_get_native_thread_number:
    case Intrinsic::cj_get_type_info:
    case Intrinsic::cj_is_subtype:
    case Intrinsic::cj_get_gc_count:
    case Intrinsic::cj_get_gc_time_us:
    case Intrinsic::cj_get_gc_freed_size:
    case Intrinsic::cj_start_cpu_profiling:
    case Intrinsic::cj_stop_cpu_profiling:
    case Intrinsic::cj_set_gc_threshold:
    case Intrinsic::cj_post_throw_exception:
    case Intrinsic::cj_register_implicit_exception_raisers:
    case Intrinsic::cj_blackhole:
    case Intrinsic::cj_get_lambda_addr:
      Lowering.replaceWithRuntimeFunc(CI, true, false);
      Changed = true;
      break;
    case Intrinsic::cj_cross_access_barrier:
    case Intrinsic::cj_get_exported_ref:
    case Intrinsic::cj_remove_exported_ref:
    case Intrinsic::cj_create_export_handle:
    case Intrinsic::cj_fill_in_stack_trace:
      Lowering.replaceWithRuntimeFunc(CI, false, false);
      Changed = true;
      break;
    case Intrinsic::cj_get_vtable_func:
      Lowering.replaceGetVTableFunc(CI);
      Changed = true;
      break;
    case Intrinsic::cj_get_mtable_func:
      Lowering.replaceGetMTableFunc(CI);
      Changed = true;
      break;
    case Intrinsic::cj_get_method_outertype:
      Lowering.replaceGetMethodOuterType(CI);
      Changed = true;
      break;
    case Intrinsic::cj_throw_exception:
      if (Triple(F.getParent()->getTargetTriple()).isOSWindows()) {
        // For windows, throw_exception need stackmap, beacuse runtime stack
        // unwinding depends on stackmap.
        Lowering.replaceWithRuntimeFunc(CI, false, false);
      } else {
        Lowering.replaceWithRuntimeFunc(CI, true, false);
      }
      Changed = true;
      break;
    case Intrinsic::cj_malloc_object: {
      Lowering.loweringMallocObject(CI);
      Changed = true;
      break;
    }
    case Intrinsic::cj_alloca_generic:
      Lowering.setHeapMallocSizeAlign(CI);
      Lowering.replaceAllocaGeneric(CI, ES);
      Changed = true;
      break;
    case Intrinsic::cj_malloc_array:
      Lowering.replaceNewArray(CI);
      CI->addRetAttr(Attribute::NoAlias);
      Changed = true;
      break;
    case Intrinsic::cj_malloc_array_generic:
      Lowering.replaceWithRuntimeFunc(CI, false, true);
      CI->addRetAttr(Attribute::NoAlias);
      Changed = true;
      break;
    case Intrinsic::cj_invoke_gc:
      Lowering.replaceWithRuntimeFunc(CI, false, false);
      Changed = true;
      break;
    case Intrinsic::cj_division_check_sdiv:
    case Intrinsic::cj_division_check_udiv:
    case Intrinsic::cj_division_check_srem:
    case Intrinsic::cj_division_check_urem:
      Lowering.markLoweringDivisionCheck(CI);
      Changed = true;
      break;
    }
  }
  Lowering.finishAll();
  return Changed;
}

PreservedAnalyses CJRuntimeLowering::run(Module &M,
                                         ModuleAnalysisManager &AM) const {
  if (!hasRunCangjieOpt(M)) {
    M.setModuleFlag(Module::Warning, "Cangjie_OPT",
                    ConstantAsMetadata::get(ConstantInt::get(
                        Type::getInt32Ty(M.getContext()), 1)));
  }
  bool Changed = false;
  auto &FAM = AM.getResult<FunctionAnalysisManagerModuleProxy>(M).getManager();
  // Declaring MCC Functions for Backend Processing.
  declareRuntimeFunc(M);
  CJIntrinsicLowering CJLowering(M);
  if (Triple(M.getTargetTriple()).isARM())
    for (Function &F : M)
      F.setAlignment(Align(16));

  // traversal Function-Instruction to lower intrinsic
  for (Function &F : M) {
    auto &TLI = FAM.getResult<TargetLibraryAnalysis>(F);
    // Insert a gv for native Func
    if (F.hasFnAttribute("cj2c") || F.hasFnAttribute("c2cj")) {
      insertGVForNativeFunc(M, F, TLI);
      Changed = true;
    }

    if (!CJLTOOpt) {
      Changed |= runtimeLoweringFunc(F, CJLowering);
    }
  }

  if (!Changed)
    return PreservedAnalyses::all();

  PreservedAnalyses PA;
  PA.preserve<TargetLibraryAnalysis>();
  return PA;
}

namespace {
class CJRuntimeLoweringLegacyPass : public ModulePass {
public:
  static char ID;

  explicit CJRuntimeLoweringLegacyPass() : ModulePass(ID) {
    initializeCJRuntimeLoweringLegacyPassPass(*PassRegistry::getPassRegistry());
  }
  ~CJRuntimeLoweringLegacyPass() = default;

  bool runOnModule(Module &M) override {
    bool Changed = false;
    // Declaring MCC Functions for Backend Processing.
    declareRuntimeFunc(M);
    CJIntrinsicLowering CJLowering(M);

    // traversal Function-Instruction to lower intrinsic
    for (Function &F : M) {
      const TargetLibraryInfo &TLI =
          getAnalysis<TargetLibraryInfoWrapperPass>().getTLI(F);
      // Insert a gv for native Func
      if (F.hasFnAttribute("cj2c") || F.hasFnAttribute("c2cj")) {
        insertGVForNativeFunc(M, F, TLI);
        Changed = true;
      }

      if (!CJLTOOpt) {
        Changed |= runtimeLoweringFunc(F, CJLowering);
      }
    }
    return Changed;
  }

  void getAnalysisUsage(AnalysisUsage &AU) const override {
    AU.addRequired<TargetLibraryInfoWrapperPass>();
  }
};
} // namespace

char CJRuntimeLoweringLegacyPass::ID = 0;

ModulePass *llvm::createCJRuntimeLoweringLegacyPass() {
  return new CJRuntimeLoweringLegacyPass();
}

INITIALIZE_PASS(CJRuntimeLoweringLegacyPass, "cj-runtime-lowering",
                "CJ Runtime Lowering", false, false)
