// Generated by runtime/tools/generate-runtime-layout.py; do not edit.
// Source of truth: runtime static_asserts; runtime must also build.
// TypeInfo offsets describe the 64-bit ABI. Thread offsets are target-specific.
#ifndef CANGJIE_RUNTIME_LAYOUT_H
#define CANGJIE_RUNTIME_LAYOUT_H
namespace CangjieRuntimeLayout {
constexpr unsigned ThreadIdAArch64Offset = 456;
constexpr unsigned ThreadIdWindowsX86Offset = 536;
constexpr unsigned ThreadIdX86Offset = 336;
constexpr unsigned MutexOwnerOffset = 8;
constexpr unsigned MutexCountOffset = 16;
constexpr unsigned MutexStateOffset = 24;
constexpr unsigned MutexLocked = 4;
constexpr unsigned ObjectStateWordOffset = 0;
constexpr unsigned ObjectHeaderSize = 8;
constexpr unsigned FuncStartPCOffsetX86 = 9;
constexpr unsigned ArrayLengthOffset = 8;
constexpr unsigned ArrayHeaderSize = 16;
constexpr unsigned TypeInfoSize = 96;
constexpr unsigned FuncDescReturnPollOffsetMachO = 32;
constexpr unsigned FuncDescReturnPollOffsetELF = 28;
namespace TypeInfo {
constexpr unsigned typeInfoNameIndex = 0;
constexpr unsigned typeInfoNameOffset = 0;
constexpr unsigned typeIndex = 1;
constexpr unsigned typeOffset = 8;
constexpr unsigned flagIndex = 2;
constexpr unsigned flagOffset = 9;
constexpr unsigned fieldNumIndex = 3;
constexpr unsigned fieldNumOffset = 10;
constexpr unsigned instanceSizeIndex = 4;
constexpr unsigned instanceSizeOffset = 12;
constexpr unsigned gctibIndex = 5;
constexpr unsigned gctibOffset = 16;
constexpr unsigned uuidIndex = 6;
constexpr unsigned uuidOffset = 24;
constexpr unsigned alignIndex = 7;
constexpr unsigned alignOffset = 28;
constexpr unsigned typeArgsNumIndex = 8;
constexpr unsigned typeArgsNumOffset = 29;
constexpr unsigned validInheritNumIndex = 9;
constexpr unsigned validInheritNumOffset = 30;
constexpr unsigned fieldOffsetsIndex = 10;
constexpr unsigned fieldOffsetsOffset = 32;
constexpr unsigned sourceGenericIndex = 11;
constexpr unsigned sourceGenericOffset = 40;
constexpr unsigned typeArgsIndex = 12;
constexpr unsigned typeArgsOffset = 48;
constexpr unsigned fieldsIndex = 13;
constexpr unsigned fieldsOffset = 56;
constexpr unsigned superTypeInfoIndex = 14;
constexpr unsigned superTypeInfoOffset = 64;
constexpr unsigned vExtensionDataStartIndex = 15;
constexpr unsigned vExtensionDataStartOffset = 72;
constexpr unsigned mTableDescIndex = 16;
constexpr unsigned mTableDescOffset = 80;
constexpr unsigned reflectInfoIndex = 17;
constexpr unsigned reflectInfoOffset = 88;
} // namespace TypeInfo
} // namespace CangjieRuntimeLayout
#endif
