//===-- CangjieTLABLayout.h - Runtime TLAB ABI --------------------*- C++ -*-===//
// Generated by llvm/utils/check-cangjie-tlab-layout.py from runtime static_asserts.
#ifndef LLVM_CODEGEN_CANGJIETLABLAYOUT_H
#define LLVM_CODEGEN_CANGJIETLABLAYOUT_H
namespace llvm {
namespace CangjieTLABLayout {
constexpr unsigned BufferOffset = 0;
constexpr unsigned TopOffset = 0;
constexpr unsigned EndOffset = 8;
} // namespace CangjieTLABLayout
} // namespace llvm
#endif
